/**
 * SEO Flavor Lookup — mapování slug → flavor_id (UUID) v Supabase databázi
 * 
 * Pouze identifikační data pro lookup. Žádná % data zde NEJSOU.
 * Procenta (min/max/recommended) se načítají AŽ z Supabase DB
 * po kliknutí na "Začít míchání" přes getFlavorById().
 */
window.SEO_FLAVORS = {
    "tpa-menthol": { flavor_id: "537a3cd9-9e6c-4e3b-b5de-7996696522f4", manufacturer_code: "TPA", name: "Menthol", manufacturer_name: "The Flavor Apprentice", category: "menthol", product_type: "vape" },
    "cap-strawberry": { flavor_id: "3f6724bc-edf6-4c39-86bf-10a20c40a4ee", manufacturer_code: "CAP", name: "Strawberry", manufacturer_name: "Capella Flavors", category: "fruit", product_type: "vape" },
    "tpa-vanilla-custard": { flavor_id: "99284c06-b2ae-4377-8698-c616af9fe804", manufacturer_code: "TPA", name: "Vanilla Custard", manufacturer_name: "The Flavor Apprentice", category: "cream", product_type: "vape" },
    "tpa-cookie": { flavor_id: "418446d0-362e-4456-aff7-ad3735e1dfc6", manufacturer_code: "TPA", name: "Cookie", manufacturer_name: "The Flavor Apprentice", category: "bakery", product_type: "vape" },
    "tpa-mango": { flavor_id: "b79a7a57-686e-436d-a40d-86ddf046ea19", manufacturer_code: "TPA", name: "Mango", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "tpa-caramel": { flavor_id: "07f3b2cb-b2b9-40a6-a01f-afaaa181b531", manufacturer_code: "TPA", name: "Caramel", manufacturer_name: "The Flavor Apprentice", category: "dessert", product_type: "vape" },
    "tpa-raspberry": { flavor_id: "78278fb9-6af9-49da-b644-66fa33eb833f", manufacturer_code: "TPA", name: "Raspberry", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "fw-blueberry": { flavor_id: "39678d05-f619-467d-a200-1aba9da38b23", manufacturer_code: "FW", name: "Blueberry", manufacturer_name: "Flavor West", category: "fruit", product_type: "vape" },
    "tpa-bavarian-cream": { flavor_id: "d4f490bc-9a94-49c6-b07b-407a723abbc5", manufacturer_code: "TPA", name: "Bavarian Cream", manufacturer_name: "The Flavor Apprentice", category: "cream", product_type: "vape" },
    "tpa-pineapple": { flavor_id: "0fc6bcef-fad6-4937-b67b-cd96fa6684c1", manufacturer_code: "TPA", name: "Pineapple", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "tpa-coconut": { flavor_id: "9b9ab40a-dd55-4c81-9f7d-4bacd4d30cd9", manufacturer_code: "TPA", name: "Coconut", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "tpa-dragonfruit": { flavor_id: "e871f3bf-9d96-4197-8719-2e6597727711", manufacturer_code: "TPA", name: "Dragonfruit", manufacturer_name: "The Flavor Apprentice", category: "tropical", product_type: "vape" },
    "tpa-peach": { flavor_id: "7f604f8f-b178-4d45-8316-713982204960", manufacturer_code: "TPA", name: "Peach", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "tpa-orange": { flavor_id: "213580f6-3e92-4ae5-82a5-5d43557fa2f9", manufacturer_code: "TPA", name: "Orange", manufacturer_name: "The Flavor Apprentice", category: "citrus", product_type: "vape" },
    "fw-apple": { flavor_id: "50977b8e-6a1b-40c2-8736-af428a82b7ac", manufacturer_code: "FW", name: "Apple", manufacturer_name: "Flavor West", category: "fruit", product_type: "vape" },
    "tpa-cheesecake": { flavor_id: "30df7581-aa58-495c-9b2f-5e9849c9f4fe", manufacturer_code: "TPA", name: "Cheesecake", manufacturer_name: "The Flavor Apprentice", category: "dessert", product_type: "vape" },
    "tpa-lemon": { flavor_id: "f14c2a6d-c4bc-4292-8eab-44ed3ac75405", manufacturer_code: "TPA", name: "Lemon", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "tpa-banana-cream": { flavor_id: "ebfd267c-5143-4ebd-abbc-9f38b5790a40", manufacturer_code: "TPA", name: "Banana Cream", manufacturer_name: "The Flavor Apprentice", category: "cream", product_type: "vape" },
    "tpa-watermelon": { flavor_id: "e08a1db8-2244-4015-9edb-6fcfdcf4af82", manufacturer_code: "TPA", name: "Watermelon", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "tpa-grape": { flavor_id: "27ef86f6-fe11-463a-8b6c-16c33d2a1add", manufacturer_code: "TPA", name: "Grape", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "fw-sweet-cream": { flavor_id: "bc24ead5-4ac2-4329-b461-5bfe3d8387fe", manufacturer_code: "FW", name: "Sweet Cream", manufacturer_name: "Flavor West", category: "cream", product_type: "vape" },
    "tpa-strawberry": { flavor_id: "0a1c05ee-cb14-41b7-a6e7-f66214b49c3d", manufacturer_code: "TPA", name: "Strawberry", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "inw-lemon": { flavor_id: "28820197-696a-4841-8fca-00e5696789f8", manufacturer_code: "INW", name: "Lemon", manufacturer_name: "Inawera", category: "fruit", product_type: "vape" },
    "inw-grape": { flavor_id: "81e43ea0-1bca-4ce9-a8d4-cb4326afbce6", manufacturer_code: "INW", name: "Grape", manufacturer_name: "Inawera", category: "fruit", product_type: "vape" },
    "fw-watermelon": { flavor_id: "e5dd6f46-6628-4ac6-95a6-56b9d3718e0a", manufacturer_code: "FW", name: "Watermelon", manufacturer_name: "Flavor West", category: "fruit", product_type: "vape" },
    "flv-vanilla-custard": { flavor_id: "b03872f5-519c-4028-81d7-aa907c62444f", manufacturer_code: "FLV", name: "Vanilla Custard", manufacturer_name: "Flavorah", category: "cream", product_type: "vape" },
    "fw-peach": { flavor_id: "bf4c5b01-c98b-43ba-bd40-bf5d6879ea5d", manufacturer_code: "FW", name: "Peach", manufacturer_name: "Flavor West", category: "fruit", product_type: "vape" },
    "fw-cheesecake": { flavor_id: "6a2b5a42-1b7e-4364-bea6-ac0fb5c4c870", manufacturer_code: "FW", name: "Cheesecake", manufacturer_name: "Flavor West", category: "bakery", product_type: "vape" },
    "inw-cookie": { flavor_id: "3f737da9-407c-46c9-818c-6f3a143e14b7", manufacturer_code: "INW", name: "Cookie", manufacturer_name: "Inawera", category: "bakery", product_type: "vape" },
    "inw-caramel": { flavor_id: "1a6ca4e8-2f13-4ab1-91cc-2fcc2b65e9f9", manufacturer_code: "INW", name: "Caramel", manufacturer_name: "Inawera", category: "dessert", product_type: "vape" },
    "inw-ry4": { flavor_id: "b43d548f-f351-4c2e-b27f-fc161197ec1f", manufacturer_code: "INW", name: "RY4", manufacturer_name: "Inawera", category: "tobacco", product_type: "vape" },
    "inw-menthol": { flavor_id: "1a1ef6ed-a79c-4e22-96b3-7bcae62b28c4", manufacturer_code: "INW", name: "Menthol", manufacturer_name: "Inawera", category: "menthol", product_type: "vape" },
    "fa-strawberry": { flavor_id: "b34c342c-e783-4b34-894a-df26f9690ac9", manufacturer_code: "FA", name: "Strawberry", manufacturer_name: "FlavourArt", category: "fruit", product_type: "vape" },
    "inw-mango": { flavor_id: "5935f526-d70d-474f-babc-3dedcbb6f18f", manufacturer_code: "INW", name: "Mango", manufacturer_name: "Inawera", category: "fruit", product_type: "vape" },
    "inw-pineapple": { flavor_id: "ef1eba3d-7cfa-44b7-a29c-1f959ac6b0f3", manufacturer_code: "INW", name: "Pineapple", manufacturer_name: "Inawera", category: "fruit", product_type: "vape" },
    "inw-coconut": { flavor_id: "df4fc92b-5e3b-40bb-b578-77c639b63c4e", manufacturer_code: "INW", name: "Coconut", manufacturer_name: "Inawera", category: "fruit", product_type: "vape" },
    "inw-blueberry": { flavor_id: "d50d1402-f648-4cb7-b1ea-5e95ef73a49f", manufacturer_code: "INW", name: "Blueberry", manufacturer_name: "Inawera", category: "fruit", product_type: "vape" },
    "inw-raspberry": { flavor_id: "9a3f6ac2-fb22-464b-b21a-be3191456ee3", manufacturer_code: "INW", name: "Raspberry", manufacturer_name: "Inawera", category: "fruit", product_type: "vape" },
    "inw-orange": { flavor_id: "0457bd7b-1d8e-4739-b1e6-dcc7bb469088", manufacturer_code: "INW", name: "Orange", manufacturer_name: "Inawera", category: "fruit", product_type: "vape" },
    "fa-mint": { flavor_id: "bc29e86c-5d2c-4b0b-934b-331e91aa19c3", manufacturer_code: "FA", name: "Mint", manufacturer_name: "FlavourArt", category: "menthol", product_type: "vape" },
    "imp-red-orange": { flavor_id: "9a5d0ed1-03e1-4cec-ab46-27d42b00640c", manufacturer_code: "IMP", name: "Red Orange", manufacturer_name: "Imperia", category: "fruit", product_type: "vape" },
    "imp-wild-strawberry": { flavor_id: "e6ae47ba-2001-4204-ab4f-c251f948ffa1", manufacturer_code: "IMP", name: "Wild Strawberry", manufacturer_name: "Imperia", category: "fruit", product_type: "vape" },
    "imp-coconut": { flavor_id: "d3a2e4d7-ee49-4dad-a5cb-c688a15960ab", manufacturer_code: "IMP", name: "Coconut", manufacturer_name: "Imperia", category: "fruit", product_type: "vape" },
    "imp-vanilla": { flavor_id: "9e3e3ecd-7866-45e4-bc42-00a44efe2613", manufacturer_code: "IMP", name: "Vanilla", manufacturer_name: "Imperia", category: "cream", product_type: "vape" },
    "tpa-cool-mint": { flavor_id: "b492a8c6-6233-442b-a592-aef2caf3685d", manufacturer_code: "TPA", name: "Cool Mint", manufacturer_name: "The Flavor Apprentice", category: "menthol", product_type: "vape" },
    "imp-caramel": { flavor_id: "77b34e86-ac09-4f27-b69f-ac81cb77a2ee", manufacturer_code: "IMP", name: "Caramel", manufacturer_name: "Imperia", category: "dessert", product_type: "vape" },
    "tfa-absinthe": { flavor_id: "a11d71b0-29cb-40cd-afe7-547ee2569dd3", manufacturer_code: "TFA", name: "Absinthe", manufacturer_name: "The Flavor Apprentice", category: "drink", product_type: "vape" },
    "imp-chocolate": { flavor_id: "6d2eb9b4-074e-4d20-ab7f-5895a6789173", manufacturer_code: "IMP", name: "Chocolate", manufacturer_name: "Imperia", category: "dessert", product_type: "vape" },
    "imp-cookie": { flavor_id: "14b37d19-1834-4bba-aa07-4fdac1b06cc1", manufacturer_code: "IMP", name: "Cookie", manufacturer_name: "Imperia", category: "bakery", product_type: "vape" },
    "imp-hazelnut": { flavor_id: "4227d583-8ab4-4768-a283-2b9dc51d91df", manufacturer_code: "IMP", name: "Hazelnut", manufacturer_name: "Imperia", category: "nuts", product_type: "vape" },
    "imp-honey": { flavor_id: "bfff87b8-541a-42a9-9a8e-2b9b1e6a88e9", manufacturer_code: "IMP", name: "Honey", manufacturer_name: "Imperia", category: "dessert", product_type: "vape" },
    "imp-custard": { flavor_id: "4e05f9a3-8226-4e25-8570-b658fabb83ff", manufacturer_code: "IMP", name: "Custard", manufacturer_name: "Imperia", category: "cream", product_type: "vape" },
    "tfa-acetyl-pyrazine-5-pg": { flavor_id: "6563d273-356b-4589-88cf-9c9208cae1cf", manufacturer_code: "TFA", name: "Acetyl Pyrazine 5 PG", manufacturer_name: "The Flavor Apprentice", category: "additive", product_type: "vape" },
    "tfa-almond-amaretto": { flavor_id: "4a1d94ae-cb43-4bdf-b373-143053d5a703", manufacturer_code: "TFA", name: "Almond Amaretto", manufacturer_name: "The Flavor Apprentice", category: "nut", product_type: "vape" },
    "imp-tiramisu": { flavor_id: "5ce67a1d-71df-4e58-afa1-ed42bb6e1839", manufacturer_code: "IMP", name: "Tiramisu", manufacturer_name: "Imperia", category: "dessert", product_type: "vape" },
    "imp-cinnamon": { flavor_id: "09f34e72-f513-4030-8777-e689944429f5", manufacturer_code: "IMP", name: "Cinnamon", manufacturer_name: "Imperia", category: "spice", product_type: "vape" },
    "tpa-peach-juicy": { flavor_id: "23a63dd3-c239-4f7c-9ea8-e7ea5af4a32e", manufacturer_code: "TPA", name: "Peach Juicy", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "alq-ananas": { flavor_id: "9d0cae74-f39e-4711-b163-3a05900b0e15", manufacturer_code: "ALQ", name: "Ananas", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "alq-banane": { flavor_id: "70eeae3f-314e-4c9d-aac9-8493742d654e", manufacturer_code: "ALQ", name: "Banane", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "imp-american-tobacco": { flavor_id: "86f56538-c8a4-44f1-b802-d834cf722014", manufacturer_code: "IMP", name: "American Tobacco", manufacturer_name: "Imperia", category: "tobacco", product_type: "vape" },
    "imp-virginia-tobacco": { flavor_id: "b6410883-5c56-430a-86e5-595a2d1e3299", manufacturer_code: "IMP", name: "Virginia Tobacco", manufacturer_name: "Imperia", category: "tobacco", product_type: "vape" },
    "imp-turkish-tobacco": { flavor_id: "7d083544-064b-4e1b-a707-e8ce4e06862c", manufacturer_code: "IMP", name: "Turkish Tobacco", manufacturer_name: "Imperia", category: "tobacco", product_type: "vape" },
    "imp-cigar": { flavor_id: "9adf0f9b-2d68-4aa6-b5e0-1d97361fe3c5", manufacturer_code: "IMP", name: "Cigar", manufacturer_name: "Imperia", category: "tobacco", product_type: "vape" },
    "tpa-absinthe": { flavor_id: "936b5d64-8b8b-4cba-8e2a-8bfe7edb3fe0", manufacturer_code: "TPA", name: "Absinthe", manufacturer_name: "The Flavor Apprentice", category: "drink", product_type: "vape" },
    "alq-mint-candy": { flavor_id: "545fae45-0ee6-4701-bd3f-9a56399e7337", manufacturer_code: "ALQ", name: "Mint Candy", manufacturer_name: "A&L (Aromes et Liquides)", category: "candy", product_type: "vape" },
    "ssa-apple-pinata-type": { flavor_id: "30d9ab38-275d-4b2f-bf1f-c5c7ffba0e4d", manufacturer_code: "SSA", name: "Apple Pinata Type", manufacturer_name: "Sobucky Super Aromas", category: "fruit", product_type: "vape" },
    "imp-ry4": { flavor_id: "77ac13cc-6a39-41ce-bb36-5f0418a53f48", manufacturer_code: "IMP", name: "RY4", manufacturer_name: "Imperia", category: "tobacco", product_type: "vape" },
    "imp-coffee": { flavor_id: "eae4cc96-3174-47a4-955e-eb5bc37e35ed", manufacturer_code: "IMP", name: "Coffee", manufacturer_name: "Imperia", category: "drink", product_type: "vape" },
    "imp-cola": { flavor_id: "52a2c561-d586-456e-bb03-4575b06eed7a", manufacturer_code: "IMP", name: "Cola", manufacturer_name: "Imperia", category: "drink", product_type: "vape" },
    "imp-energy-drink": { flavor_id: "838a9ea2-3134-4d62-85f9-d3a1b4ba4803", manufacturer_code: "IMP", name: "Energy Drink", manufacturer_name: "Imperia", category: "drink", product_type: "vape" },
    "imp-cappuccino": { flavor_id: "13a93cb8-c601-4e4b-b986-14e4198b85ea", manufacturer_code: "IMP", name: "Cappuccino", manufacturer_name: "Imperia", category: "drink", product_type: "vape" },
    "ssa-apricot": { flavor_id: "daa7bda2-cb2c-482d-91a5-861365a7cdff", manufacturer_code: "SSA", name: "Apricot", manufacturer_name: "Sobucky Super Aromas", category: "fruit", product_type: "vape" },
    "alq-cassis-v2": { flavor_id: "56b6bcd3-be95-4a5d-a2a5-06ee3edf297e", manufacturer_code: "ALQ", name: "Cassis V2", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "imp-menthol": { flavor_id: "9dd7a95c-1cd1-4570-861d-80486321255e", manufacturer_code: "IMP", name: "Menthol", manufacturer_name: "Imperia", category: "menthol", product_type: "vape" },
    "alq-cerise": { flavor_id: "5d6f5f08-101d-47d9-8955-cc8daed6b701", manufacturer_code: "ALQ", name: "Cerise", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "alq-citron": { flavor_id: "cf885bf6-3e50-4225-b3ef-1f1e791bbd44", manufacturer_code: "ALQ", name: "Citron", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "ssa-banana-real-ripe-type": { flavor_id: "4d3d67bf-88eb-44fc-aea4-eec9c6e175c3", manufacturer_code: "SSA", name: "Banana Real Ripe Type", manufacturer_name: "Sobucky Super Aromas", category: "fruit", product_type: "vape" },
    "tpa-apple-tart-granny-smith": { flavor_id: "96129d22-edaf-478c-83d4-75a764380f25", manufacturer_code: "TPA", name: "Apple (Tart Granny Smith)", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "imp-mint": { flavor_id: "9eeaae43-8e0a-4d80-becc-ca723f44432b", manufacturer_code: "IMP", name: "Mint", manufacturer_name: "Imperia", category: "menthol", product_type: "vape" },
    "imp-spearmint": { flavor_id: "46e3e289-2fcc-4f5e-baa5-500504d5a68c", manufacturer_code: "IMP", name: "Spearmint", manufacturer_name: "Imperia", category: "menthol", product_type: "vape" },
    "imp-ice-menthol": { flavor_id: "6b7dacbb-1b2e-4aa9-89f2-96eba0729b5e", manufacturer_code: "IMP", name: "Ice Menthol", manufacturer_name: "Imperia", category: "menthol", product_type: "vape" },
    "ssa-blackcurrant": { flavor_id: "3bf28828-9a6c-4025-bc7a-d70f9d429de2", manufacturer_code: "SSA", name: "Blackcurrant", manufacturer_name: "Sobucky Super Aromas", category: "fruit", product_type: "vape" },
    "inw-yes-we-cheesecake": { flavor_id: "ea33752e-e5cd-493d-ae5d-3572fa5b3f95", manufacturer_code: "INW", name: "Yes We Cheesecake", manufacturer_name: "Inawera", category: "dessert", product_type: "vape" },
    "inw-peach": { flavor_id: "3a1a1aa7-a503-4b05-96b3-2f048b0b65b8", manufacturer_code: "INW", name: "Peach", manufacturer_name: "Inawera", category: "fruit", product_type: "vape" },
    "inw-marzipan": { flavor_id: "08bab307-dbd2-4555-993c-f86faf1e35f2", manufacturer_code: "INW", name: "Marzipan", manufacturer_name: "Inawera", category: "nuts", product_type: "vape" },
    "inw-dark-chocolate": { flavor_id: "5ac691f6-4703-4938-907b-a7b2296c6997", manufacturer_code: "INW", name: "Dark Chocolate", manufacturer_name: "Inawera", category: "dessert", product_type: "vape" },
    "inw-waffle": { flavor_id: "5b0385f0-4ac7-42f8-ab87-fd7cf0014056", manufacturer_code: "INW", name: "Waffle", manufacturer_name: "Inawera", category: "bakery", product_type: "vape" },
    "inw-coffee": { flavor_id: "cc027e30-e8b1-41b0-bcbc-551345aba9c5", manufacturer_code: "INW", name: "Coffee", manufacturer_name: "Inawera", category: "drink", product_type: "vape" },
    "tpa-acai": { flavor_id: "ae7e06a9-eaa1-4642-834d-7433d6508bb3", manufacturer_code: "TPA", name: "Acai", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "inw-dnb-donut": { flavor_id: "e18436f9-4424-4c9a-8903-b4728d8f5f9b", manufacturer_code: "INW", name: "DNB (Donut)", manufacturer_name: "Inawera", category: "bakery", product_type: "vape" },
    "fa-kiwi": { flavor_id: "fba5eb84-4d1d-487f-983c-c389a29eefc9", manufacturer_code: "FA", name: "Kiwi", manufacturer_name: "FlavourArt", category: "tropical", product_type: "vape" },
    "fa-tiramisu": { flavor_id: "5cc7ba57-b331-435c-a8a3-cfb175c54343", manufacturer_code: "FA", name: "Tiramisu", manufacturer_name: "FlavourArt", category: "dessert", product_type: "vape" },
    "tpa-apple-candy": { flavor_id: "1c928524-ee34-43f4-a4c9-656cc43cb607", manufacturer_code: "TPA", name: "Apple Candy", manufacturer_name: "The Flavor Apprentice", category: "candy", product_type: "vape" },
    "tpa-berry-mix": { flavor_id: "ea096fbc-5bf4-47be-8cfe-0ce474e66015", manufacturer_code: "TPA", name: "Berry Mix", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "vv-dawn": { flavor_id: "213260e4-ca82-4146-8576-34d6e7beca7a", manufacturer_code: "VV", name: "Dawn", manufacturer_name: "Vampire Vape", category: "fruit", product_type: "vape" },
    "tfa-apple-tart-granny-smith": { flavor_id: "f950a41e-5e01-4e61-8720-d3fd12ea9c59", manufacturer_code: "TFA", name: "Apple Tart Granny Smith", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "inw-tobacco-absolute-cigar": { flavor_id: "f860c31f-897e-4147-a63a-2a698e76ff58", manufacturer_code: "INW", name: "Tobacco Absolute Cigar", manufacturer_name: "Inawera", category: "tobacco", product_type: "vape" },
    "inw-tobacco-classic": { flavor_id: "fa4f2e32-de38-452e-af5e-2eb450828e67", manufacturer_code: "INW", name: "Tobacco Classic", manufacturer_name: "Inawera", category: "tobacco", product_type: "vape" },
    "inw-tobacco-gold-ducat": { flavor_id: "b161a843-02b1-479d-93a5-25122fe47c7b", manufacturer_code: "INW", name: "Tobacco Gold Ducat", manufacturer_name: "Inawera", category: "tobacco", product_type: "vape" },
    "tfa-bacon": { flavor_id: "65b3268d-8527-4dd3-8458-dbef98ee5dcd", manufacturer_code: "TFA", name: "Bacon", manufacturer_name: "The Flavor Apprentice", category: "other", product_type: "vape" },
    "tfa-banana-nut-bread": { flavor_id: "ab79c51b-1393-4533-a957-cc0c2100349c", manufacturer_code: "TFA", name: "Banana Nut Bread", manufacturer_name: "The Flavor Apprentice", category: "bakery", product_type: "vape" },
    "cap-vanilla-custard": { flavor_id: "0022c000-2800-46f7-a0c3-63a961fd7fcf", manufacturer_code: "CAP", name: "Vanilla Custard", manufacturer_name: "Capella Flavors", category: "dessert", product_type: "vape" },
    "fa-forest-fruit": { flavor_id: "692920c5-4015-49a3-a7dc-04b5f8a613fc", manufacturer_code: "FA", name: "Forest Fruit", manufacturer_name: "FlavourArt", category: "berry", product_type: "vape" },
    "alq-citron-vert": { flavor_id: "e96724e1-a89b-4d1d-a61e-6bb0bd1e9a09", manufacturer_code: "ALQ", name: "Citron Vert", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "alq-fraise": { flavor_id: "7c196899-7826-475d-b899-7564eab7920b", manufacturer_code: "ALQ", name: "Fraise", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "alq-fraise-des-bois": { flavor_id: "37d828ac-259c-46d9-89e3-4c06aef0bbda", manufacturer_code: "ALQ", name: "Fraise des Bois", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "alq-framboise": { flavor_id: "3763f2b7-0394-459a-baec-08a60a3b0497", manufacturer_code: "ALQ", name: "Framboise", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "alq-fruit-du-dragon": { flavor_id: "fbc8536b-4d89-4730-8b1e-76bb3899ca5b", manufacturer_code: "ALQ", name: "Fruit du Dragon", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "alq-fruits-rouges": { flavor_id: "3219b6bc-c01d-4031-a294-aacea572761f", manufacturer_code: "ALQ", name: "Fruits Rouges", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "tfa-berry-crunch-cereal": { flavor_id: "d3f719a9-11e8-4a88-86a8-980fa9f4ee9c", manufacturer_code: "TFA", name: "Berry Crunch Cereal", manufacturer_name: "The Flavor Apprentice", category: "cereal", product_type: "vape" },
    "alq-fruits-de-la-passion": { flavor_id: "2a1fa153-714a-4e0c-8544-2d5a737786cf", manufacturer_code: "ALQ", name: "Fruits de la Passion", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "alq-fruits-exotiques": { flavor_id: "099a2f90-7e6b-4337-b677-8293732c9f08", manufacturer_code: "ALQ", name: "Fruits Exotiques", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "alq-kiwi": { flavor_id: "a2eb489e-db90-4daa-9fb6-968c5bead816", manufacturer_code: "ALQ", name: "Kiwi", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "fa-catania": { flavor_id: "22b34a24-5e25-4edf-8f16-599b43ee92aa", manufacturer_code: "FA", name: "Catania", manufacturer_name: "FlavourArt", category: "tobacco", product_type: "vape" },
    "alq-litchi": { flavor_id: "cf1849c3-02a7-4203-be51-9dc1cba424e5", manufacturer_code: "ALQ", name: "Litchi", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "alq-mangue": { flavor_id: "f871e512-4961-4b97-bfeb-dce3c8a8089a", manufacturer_code: "ALQ", name: "Mangue", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "fa-espresso": { flavor_id: "2a849043-0713-46d9-ad0f-ba183be88b21", manufacturer_code: "FA", name: "Espresso", manufacturer_name: "FlavourArt", category: "drink", product_type: "vape" },
    "inw-eucalyptus-mint": { flavor_id: "45861f4e-70f8-4ae2-aed0-49d7b0154781", manufacturer_code: "INW", name: "Eucalyptus Mint", manufacturer_name: "Inawera", category: "menthol", product_type: "vape" },
    "vdlv-menthe": { flavor_id: "5a06e642-bd62-4a34-8714-20c60888ab5f", manufacturer_code: "VDLV", name: "Menthe", manufacturer_name: "Vincent Dans Les Vapes", category: "menthol", product_type: "vape" },
    "ssa-cactus": { flavor_id: "476d5f8f-f756-49b6-9be3-fe3ee8725132", manufacturer_code: "SSA", name: "Cactus", manufacturer_name: "Sobucky Super Aromas", category: "fruit", product_type: "vape" },
    "ssa-whipped-cream": { flavor_id: "3bf513f1-84ac-418d-978f-c9f6e9df0f66", manufacturer_code: "SSA", name: "Whipped Cream", manufacturer_name: "Sobucky Super Aromas", category: "cream", product_type: "vape" },
    "tpa-apricot": { flavor_id: "7fcc7eb2-807c-4c0a-8186-0e565d68776b", manufacturer_code: "TPA", name: "Apricot", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "tfa-black-cherry": { flavor_id: "d5b3fd15-56fa-45b4-93a1-2b06166d32bf", manufacturer_code: "TFA", name: "Black Cherry", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "ssa-clotted-cream": { flavor_id: "8f093502-cdda-4b84-b766-300d1e6a31c4", manufacturer_code: "SSA", name: "Clotted Cream", manufacturer_name: "Sobucky Super Aromas", category: "cream", product_type: "vape" },
    "ssa-butter-cream": { flavor_id: "e878e3db-6173-4651-aef1-d0ffc9e5c808", manufacturer_code: "SSA", name: "Butter Cream", manufacturer_name: "Sobucky Super Aromas", category: "cream", product_type: "vape" },
    "vv-parma-violets": { flavor_id: "82b66b4b-fef0-47fd-a15c-3fd22b52bd22", manufacturer_code: "VV", name: "Parma Violets", manufacturer_name: "Vampire Vape", category: "candy", product_type: "vape" },
    "vv-cool-red-lips": { flavor_id: "b78e2e71-2eb0-43ac-8efa-d0fa24236293", manufacturer_code: "VV", name: "Cool Red Lips", manufacturer_name: "Vampire Vape", category: "fruit", product_type: "vape" },
    "vv-blue-ice": { flavor_id: "a0babd77-d2ee-4b98-8ebc-f0a913e9e475", manufacturer_code: "VV", name: "Blue Ice", manufacturer_name: "Vampire Vape", category: "menthol", product_type: "vape" },
    "ssa-borneo-vanilla": { flavor_id: "78cb2886-6dd9-489d-bb49-5699b49964b0", manufacturer_code: "SSA", name: "Borneo Vanilla", manufacturer_name: "Sobucky Super Aromas", category: "cream", product_type: "vape" },
    "ssa-bubblegum-fruity-type": { flavor_id: "e7ca5f3b-0957-49a4-be94-6f35271cf3bd", manufacturer_code: "SSA", name: "Bubblegum Fruity Type", manufacturer_name: "Sobucky Super Aromas", category: "candy", product_type: "vape" },
    "ssa-candy-floss": { flavor_id: "0a899e08-080c-49b3-8bc3-f87f1c9f643f", manufacturer_code: "SSA", name: "Candy Floss", manufacturer_name: "Sobucky Super Aromas", category: "candy", product_type: "vape" },
    "inw-grapes": { flavor_id: "aaa96737-f0df-42f6-a4d1-7bc0daf658e4", manufacturer_code: "INW", name: "Grapes", manufacturer_name: "Inawera", category: "fruit", product_type: "vape" },
    "ssa-candy-cuckoo": { flavor_id: "f7daab7a-da86-4212-8a26-3fe2b6f059ef", manufacturer_code: "SSA", name: "Candy Cuckoo", manufacturer_name: "Sobucky Super Aromas", category: "candy", product_type: "vape" },
    "inw-blackcurrant": { flavor_id: "cbbe823d-d6f3-4138-b25a-3426a39b6650", manufacturer_code: "INW", name: "Blackcurrant", manufacturer_name: "Inawera", category: "fruit", product_type: "vape" },
    "ssa-candy-licorice": { flavor_id: "31fa959e-9167-425c-aea9-54e0ba5cabad", manufacturer_code: "SSA", name: "Candy Licorice", manufacturer_name: "Sobucky Super Aromas", category: "candy", product_type: "vape" },
    "ssa-anise": { flavor_id: "f93079a9-b9a2-4801-995b-1ee2353e66f0", manufacturer_code: "SSA", name: "Anise", manufacturer_name: "Sobucky Super Aromas", category: "spice", product_type: "vape" },
    "vv-sherbet-lemon": { flavor_id: "b893b092-beb3-4318-af5c-f839c01a6422", manufacturer_code: "VV", name: "Sherbet Lemon", manufacturer_name: "Vampire Vape", category: "candy", product_type: "vape" },
    "vv-spearmint": { flavor_id: "50d0d9c2-504b-4845-b6f3-27f36a3014c6", manufacturer_code: "VV", name: "Spearmint", manufacturer_name: "Vampire Vape", category: "menthol", product_type: "vape" },
    "fa-cola": { flavor_id: "c1daca83-c8b3-4d01-964d-4461d451c1e5", manufacturer_code: "FA", name: "Cola", manufacturer_name: "FlavourArt", category: "drink", product_type: "vape" },
    "fa-arctic-winter": { flavor_id: "85ba93bb-5e0b-435e-8928-896452830385", manufacturer_code: "FA", name: "Arctic Winter", manufacturer_name: "FlavourArt", category: "menthol", product_type: "vape" },
    "fa-peppermint": { flavor_id: "f1a0b80f-de0c-4614-aba8-11abd65794c0", manufacturer_code: "FA", name: "Peppermint", manufacturer_name: "FlavourArt", category: "menthol", product_type: "vape" },
    "inw-shisha-raspberry": { flavor_id: "22a18ba5-b577-4922-8abe-49b621eb1f0d", manufacturer_code: "INW", name: "Shisha Raspberry", manufacturer_name: "Inawera", category: "fruit", product_type: "vape" },
    "inw-tobacco-dnb": { flavor_id: "e88672c4-1742-4540-891b-b085d1412179", manufacturer_code: "INW", name: "Tobacco DNB", manufacturer_name: "Inawera", category: "tobacco", product_type: "vape" },
    "tfa-black-currant": { flavor_id: "8e04e896-0dcc-462c-9232-508e97d4a110", manufacturer_code: "TFA", name: "Black Currant", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "tfa-black-honey": { flavor_id: "f1ded9cf-839e-4d14-b15a-bc370e6edb01", manufacturer_code: "TFA", name: "Black Honey", manufacturer_name: "The Flavor Apprentice", category: "tobacco", product_type: "vape" },
    "tfa-blackberry": { flavor_id: "855b045e-8a4c-4abf-8828-c404030a1f74", manufacturer_code: "TFA", name: "Blackberry", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "tfa-blueberry-extra": { flavor_id: "f6ba6d82-e442-4a35-b79b-deaebfa4027e", manufacturer_code: "TFA", name: "Blueberry Extra", manufacturer_name: "The Flavor Apprentice", category: "fruit", product_type: "vape" },
    "tfa-brown-sugar": { flavor_id: "d16e706b-d66e-4410-b793-29f9037af843", manufacturer_code: "TFA", name: "Brown Sugar", manufacturer_name: "The Flavor Apprentice", category: "additive", product_type: "vape" },
    "alq-melon": { flavor_id: "7bb8cf97-7da9-414c-8f26-d5b3a7a5be28", manufacturer_code: "ALQ", name: "Melon", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" },
    "alq-mure": { flavor_id: "ba1fc30c-2a29-4889-96c5-22edc08486ce", manufacturer_code: "ALQ", name: "Mure", manufacturer_name: "A&L (Aromes et Liquides)", category: "fruit", product_type: "vape" }
};
