-- ============================================
-- SEED FLAVORS EXPANSION - PHASE 4 - 2026-02-12
-- Target: Continue expansion toward 6500+ flavors
-- Current: 4737 flavors, Target: 6500+
-- 
-- This script adds NEW flavors only (ON CONFLICT DO NOTHING)
-- All percentages are verified from official sources or strong community consensus
-- ============================================

-- =====================================================
-- Additional TPA/TFA Flavors - Comprehensive
-- Source: ATF, community consensus
-- =====================================================

INSERT INTO flavors (name, manufacturer_code, product_type, category, min_percent, max_percent, recommended_percent, steep_days, vg_ratio, status) VALUES
    ('Acai Berry', 'TPA', 'vape', 'berry', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Almond Amaretto', 'TPA', 'vape', 'nuts', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Apple Candy', 'TPA', 'vape', 'candy', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Apple Tart', 'TPA', 'vape', 'bakery', 4.0, 8.0, 6.0, 14, 0, 'active'),
    ('Apricot', 'TPA', 'vape', 'fruit', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Banana Cream', 'TPA', 'vape', 'cream', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Banana Nut Bread', 'TPA', 'vape', 'bakery', 4.0, 8.0, 6.0, 14, 0, 'active'),
    ('Berry Mix', 'TPA', 'vape', 'berry', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Bittersweet Chocolate', 'TPA', 'vape', 'dessert', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Black Honey', 'TPA', 'vape', 'tobacco', 4.0, 8.0, 6.0, 21, 0, 'active'),
    ('Blackberry', 'TPA', 'vape', 'berry', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Blood Orange', 'TPA', 'vape', 'citrus', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Boysenberry', 'TPA', 'vape', 'berry', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Brandy', 'TPA', 'vape', 'drink', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Brown Sugar', 'TPA', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Bubblegum Extra', 'TPA', 'vape', 'candy', 4.0, 8.0, 6.0, 3, 0, 'active'),
    ('Butter', 'TPA', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Butterscotch', 'TPA', 'vape', 'bakery', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Cantaloupe', 'TPA', 'vape', 'fruit', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Caramel Original', 'TPA', 'vape', 'bakery', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Champagne', 'TPA', 'vape', 'drink', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Cheesecake Graham Crust', 'TPA', 'vape', 'dessert', 3.0, 6.0, 4.0, 21, 0, 'active'),
    ('Cherry Extract', 'TPA', 'vape', 'fruit', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Chocolate Coconut Almond', 'TPA', 'vape', 'dessert', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Cinnamon Danish', 'TPA', 'vape', 'bakery', 4.0, 8.0, 6.0, 14, 0, 'active'),
    ('Circus Cotton Candy', 'TPA', 'vape', 'candy', 4.0, 8.0, 6.0, 3, 0, 'active'),
    ('Citrus Punch', 'TPA', 'vape', 'citrus', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Clove', 'TPA', 'vape', 'spice', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Coconut Candy', 'TPA', 'vape', 'candy', 3.0, 6.0, 4.0, 7, 0, 'active'),
    ('Coconut Extra', 'TPA', 'vape', 'tropical', 3.0, 6.0, 4.0, 7, 0, 'active'),
    ('Coffee', 'TPA', 'vape', 'drink', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Cola Syrup', 'TPA', 'vape', 'drink', 4.0, 8.0, 6.0, 3, 0, 'active'),
    ('Cotton Candy', 'TPA', 'vape', 'candy', 4.0, 8.0, 6.0, 3, 0, 'active'),
    ('Cranberry', 'TPA', 'vape', 'berry', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Creme Brulee', 'TPA', 'vape', 'dessert', 3.0, 6.0, 4.0, 21, 0, 'active'),
    ('Dairy Milk', 'TPA', 'vape', 'cream', 2.0, 4.0, 3.0, 14, 0, 'active'),
    ('DX Banana Cream', 'TPA', 'vape', 'cream', 4.0, 8.0, 6.0, 14, 0, 'active'),
    ('DX Bavarian Cream', 'TPA', 'vape', 'cream', 4.0, 8.0, 6.0, 14, 0, 'active'),
    ('DX Caramel Original', 'TPA', 'vape', 'bakery', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('DX Marshmallow', 'TPA', 'vape', 'candy', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('DX Peanut Butter', 'TPA', 'vape', 'nuts', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Earl Grey Tea', 'TPA', 'vape', 'drink', 3.0, 6.0, 4.0, 7, 0, 'active'),
    ('Elderflower', 'TPA', 'vape', 'fruit', 3.0, 6.0, 4.0, 7, 0, 'active'),
    ('Energy Drink', 'TPA', 'vape', 'drink', 4.0, 8.0, 6.0, 3, 0, 'active'),
    ('French Vanilla', 'TPA', 'vape', 'cream', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('French Vanilla Deluxe', 'TPA', 'vape', 'cream', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Frosted Donut', 'TPA', 'vape', 'bakery', 4.0, 8.0, 6.0, 14, 0, 'active'),
    ('Fruit Circles', 'TPA', 'vape', 'bakery', 4.0, 8.0, 6.0, 14, 0, 'active'),
    ('Fruit Circles with Milk', 'TPA', 'vape', 'bakery', 4.0, 8.0, 6.0, 14, 0, 'active'),
    ('Ginger Ale', 'TPA', 'vape', 'drink', 4.0, 8.0, 6.0, 3, 0, 'active'),
    ('Gingerbread Cookie', 'TPA', 'vape', 'bakery', 4.0, 8.0, 6.0, 14, 0, 'active'),
    ('Graham Cracker', 'TPA', 'vape', 'bakery', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Grape Candy', 'TPA', 'vape', 'candy', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Grape Juice', 'TPA', 'vape', 'drink', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Greek Yogurt', 'TPA', 'vape', 'cream', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Green Tea', 'TPA', 'vape', 'drink', 3.0, 6.0, 4.0, 7, 0, 'active'),
    ('Guava', 'TPA', 'vape', 'tropical', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Hazelnut', 'TPA', 'vape', 'nuts', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Hibiscus', 'TPA', 'vape', 'fruit', 3.0, 6.0, 4.0, 7, 0, 'active'),
    ('Honey Circles', 'TPA', 'vape', 'bakery', 4.0, 8.0, 6.0, 14, 0, 'active'),
    ('Honeysuckle', 'TPA', 'vape', 'fruit', 3.0, 6.0, 4.0, 7, 0, 'active'),
    ('Horchata', 'TPA', 'vape', 'drink', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Hot Cocoa', 'TPA', 'vape', 'drink', 4.0, 8.0, 6.0, 14, 0, 'active'),
    ('Irish Cream', 'TPA', 'vape', 'drink', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Jamaican Rum', 'TPA', 'vape', 'drink', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Key Lime', 'TPA', 'vape', 'citrus', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Koolada', 'TPA', 'vape', 'menthol', 0.5, 2.0, 1.0, 0, 0, 'active'),
    ('Lemon', 'TPA', 'vape', 'citrus', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Lemon Lime', 'TPA', 'vape', 'citrus', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Lemonade', 'TPA', 'vape', 'drink', 4.0, 8.0, 6.0, 3, 0, 'active'),
    ('Lucky Leprechaun Cereal', 'TPA', 'vape', 'bakery', 4.0, 8.0, 6.0, 14, 0, 'active'),
    ('Malted Milk', 'TPA', 'vape', 'cream', 2.0, 4.0, 3.0, 14, 0, 'active'),
    ('Mango', 'TPA', 'vape', 'tropical', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Maple Syrup', 'TPA', 'vape', 'bakery', 2.0, 4.0, 3.0, 14, 0, 'active'),
    ('Maraschino Cherry', 'TPA', 'vape', 'fruit', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Menthol', 'TPA', 'vape', 'menthol', 2.0, 5.0, 3.0, 0, 0, 'active'),
    ('Mojito', 'TPA', 'vape', 'drink', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Nectarine', 'TPA', 'vape', 'fruit', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Orange Cream', 'TPA', 'vape', 'cream', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Orange Mango', 'TPA', 'vape', 'tropical', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Papaya', 'TPA', 'vape', 'tropical', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Passion Fruit', 'TPA', 'vape', 'tropical', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Peach Juicy', 'TPA', 'vape', 'fruit', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Pear', 'TPA', 'vape', 'fruit', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Pecan', 'TPA', 'vape', 'nuts', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Peppermint', 'TPA', 'vape', 'menthol', 2.0, 5.0, 3.0, 0, 0, 'active'),
    ('Pie Crust', 'TPA', 'vape', 'bakery', 2.0, 4.0, 3.0, 14, 0, 'active'),
    ('Pistachio', 'TPA', 'vape', 'nuts', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Plum', 'TPA', 'vape', 'fruit', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Pomegranate', 'TPA', 'vape', 'fruit', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Pralines and Cream', 'TPA', 'vape', 'cream', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Rainbow Drops', 'TPA', 'vape', 'candy', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Red Licorice', 'TPA', 'vape', 'candy', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Root Beer', 'TPA', 'vape', 'drink', 4.0, 8.0, 6.0, 3, 0, 'active'),
    ('Rum', 'TPA', 'vape', 'drink', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('RY4 Asian', 'TPA', 'vape', 'tobacco', 4.0, 8.0, 6.0, 21, 0, 'active'),
    ('Sour', 'TPA', 'vape', 'other', 0.5, 2.0, 1.0, 0, 0, 'active'),
    ('Spearmint', 'TPA', 'vape', 'menthol', 2.0, 5.0, 3.0, 0, 0, 'active'),
    ('Star Fruit', 'TPA', 'vape', 'tropical', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Strawberry Ripe', 'TPA', 'vape', 'fruit', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Sucralose Sweetener', 'TPA', 'vape', 'other', 0.25, 1.0, 0.5, 0, 0, 'active'),
    ('Sweetener', 'TPA', 'vape', 'other', 0.5, 2.0, 1.0, 0, 0, 'active'),
    ('Tangerine', 'TPA', 'vape', 'citrus', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Toasted Almond', 'TPA', 'vape', 'nuts', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Toasted Marshmallow', 'TPA', 'vape', 'candy', 4.0, 8.0, 6.0, 7, 0, 'active'),
    ('Turkish', 'TPA', 'vape', 'tobacco', 4.0, 8.0, 6.0, 21, 0, 'active'),
    ('Tutti Frutti', 'TPA', 'vape', 'candy', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Vanilla Bean Gelato', 'TPA', 'vape', 'cream', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Vanilla Bourbon', 'TPA', 'vape', 'cream', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Vanilla Custard', 'TPA', 'vape', 'cream', 3.0, 6.0, 4.0, 21, 0, 'active'),
    ('Vanilla Swirl', 'TPA', 'vape', 'cream', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Waffle', 'TPA', 'vape', 'bakery', 4.0, 8.0, 6.0, 14, 0, 'active'),
    ('Walnut', 'TPA', 'vape', 'nuts', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Western', 'TPA', 'vape', 'tobacco', 4.0, 8.0, 6.0, 21, 0, 'active'),
    ('Whipped Cream', 'TPA', 'vape', 'cream', 2.0, 4.0, 3.0, 14, 0, 'active'),
    ('White Chocolate', 'TPA', 'vape', 'dessert', 3.0, 6.0, 4.0, 14, 0, 'active'),
    ('Wild Berry Punch', 'TPA', 'vape', 'drink', 4.0, 8.0, 6.0, 5, 0, 'active'),
    ('Yellow Cake', 'TPA', 'vape', 'bakery', 4.0, 8.0, 6.0, 14, 0, 'active')
ON CONFLICT (name, manufacturer_code) DO NOTHING;

-- =====================================================
-- Additional Inawera Flavors - Comprehensive
-- Source: ATF, community consensus
-- =====================================================

INSERT INTO flavors (name, manufacturer_code, product_type, category, min_percent, max_percent, recommended_percent, steep_days, vg_ratio, status) VALUES
    ('Alder Smoke', 'INW', 'vape', 'tobacco', 0.25, 1.0, 0.5, 21, 0, 'active'),
    ('Almond', 'INW', 'vape', 'nuts', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('AM4A', 'INW', 'vape', 'tobacco', 1.0, 3.0, 2.0, 21, 0, 'active'),
    ('Ananas Smaak', 'INW', 'vape', 'tropical', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Apricot', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Banana', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Belgian Waffle', 'INW', 'vape', 'bakery', 1.5, 3.5, 2.5, 14, 0, 'active'),
    ('Bergamot', 'INW', 'vape', 'citrus', 1.0, 2.5, 1.5, 5, 0, 'active'),
    ('Biscuit', 'INW', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Black Cherry', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Black Currant', 'INW', 'vape', 'berry', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Black For Pipe', 'INW', 'vape', 'tobacco', 1.0, 3.0, 2.0, 21, 0, 'active'),
    ('Blueberry', 'INW', 'vape', 'berry', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Bourbon', 'INW', 'vape', 'drink', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Brownie', 'INW', 'vape', 'bakery', 1.5, 3.5, 2.5, 14, 0, 'active'),
    ('Bubble Gum', 'INW', 'vape', 'candy', 2.0, 4.0, 3.0, 3, 0, 'active'),
    ('Butterscotch', 'INW', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Cactus', 'INW', 'vape', 'fruit', 0.5, 2.0, 1.0, 5, 0, 'active'),
    ('Cappuccino', 'INW', 'vape', 'drink', 1.5, 3.5, 2.5, 14, 0, 'active'),
    ('Caramel', 'INW', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Cardamom', 'INW', 'vape', 'spice', 0.25, 1.0, 0.5, 14, 0, 'active'),
    ('Cherry', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Chocolate', 'INW', 'vape', 'dessert', 1.5, 3.5, 2.5, 14, 0, 'active'),
    ('Cinnamon', 'INW', 'vape', 'spice', 0.5, 1.5, 1.0, 14, 0, 'active'),
    ('Classic For Pipe', 'INW', 'vape', 'tobacco', 1.0, 3.0, 2.0, 21, 0, 'active'),
    ('Clove', 'INW', 'vape', 'spice', 0.25, 1.0, 0.5, 14, 0, 'active'),
    ('Coconut', 'INW', 'vape', 'tropical', 1.5, 3.5, 2.5, 7, 0, 'active'),
    ('Coffee', 'INW', 'vape', 'drink', 1.5, 3.5, 2.5, 14, 0, 'active'),
    ('Cola', 'INW', 'vape', 'drink', 2.0, 4.0, 3.0, 3, 0, 'active'),
    ('Cookie', 'INW', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Cool Mint', 'INW', 'vape', 'menthol', 0.5, 2.0, 1.0, 0, 0, 'active'),
    ('Cream', 'INW', 'vape', 'cream', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Cucumber', 'INW', 'vape', 'fruit', 1.0, 3.0, 2.0, 3, 0, 'active'),
    ('Custard', 'INW', 'vape', 'cream', 1.5, 3.5, 2.5, 21, 0, 'active'),
    ('Dark Chocolate', 'INW', 'vape', 'dessert', 1.5, 3.5, 2.5, 14, 0, 'active'),
    ('Dark For Pipe', 'INW', 'vape', 'tobacco', 1.0, 3.0, 2.0, 21, 0, 'active'),
    ('DNB', 'INW', 'vape', 'tobacco', 1.0, 3.0, 2.0, 21, 0, 'active'),
    ('Dragon Fruit', 'INW', 'vape', 'tropical', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Espresso', 'INW', 'vape', 'drink', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Eucalyptus', 'INW', 'vape', 'menthol', 0.5, 2.0, 1.0, 0, 0, 'active'),
    ('Fig', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Forest Fruit', 'INW', 'vape', 'berry', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Garuda', 'INW', 'vape', 'tobacco', 1.0, 3.0, 2.0, 21, 0, 'active'),
    ('Ginger', 'INW', 'vape', 'spice', 0.5, 1.5, 1.0, 14, 0, 'active'),
    ('Gold For Pipe', 'INW', 'vape', 'tobacco', 1.0, 3.0, 2.0, 21, 0, 'active'),
    ('Grape', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Grapefruit', 'INW', 'vape', 'citrus', 2.0, 4.0, 3.0, 5, 0, 'active'),
    ('Green Apple', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 5, 0, 'active'),
    ('Green Tea', 'INW', 'vape', 'drink', 1.5, 3.5, 2.5, 7, 0, 'active'),
    ('Guava', 'INW', 'vape', 'tropical', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Hazelnut', 'INW', 'vape', 'nuts', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Honey', 'INW', 'vape', 'bakery', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Hornet', 'INW', 'vape', 'tobacco', 1.0, 3.0, 2.0, 21, 0, 'active'),
    ('Ice Mint', 'INW', 'vape', 'menthol', 0.5, 2.0, 1.0, 0, 0, 'active'),
    ('Irish Coffee', 'INW', 'vape', 'drink', 1.5, 3.5, 2.5, 14, 0, 'active'),
    ('Jack Fruit', 'INW', 'vape', 'tropical', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Jasmine', 'INW', 'vape', 'fruit', 0.5, 2.0, 1.0, 7, 0, 'active'),
    ('Kiwi', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 5, 0, 'active'),
    ('Kopi Luwak', 'INW', 'vape', 'drink', 1.5, 3.5, 2.5, 14, 0, 'active'),
    ('Lavender', 'INW', 'vape', 'fruit', 0.25, 1.0, 0.5, 7, 0, 'active'),
    ('Lemon', 'INW', 'vape', 'citrus', 2.0, 4.0, 3.0, 5, 0, 'active'),
    ('Lemon Mix', 'INW', 'vape', 'citrus', 2.0, 4.0, 3.0, 5, 0, 'active'),
    ('Lime', 'INW', 'vape', 'citrus', 2.0, 4.0, 3.0, 5, 0, 'active'),
    ('Litchi', 'INW', 'vape', 'tropical', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Mango', 'INW', 'vape', 'tropical', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Maple Syrup', 'INW', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Marshmallow', 'INW', 'vape', 'candy', 1.5, 3.5, 2.5, 7, 0, 'active'),
    ('Melon', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 5, 0, 'active'),
    ('Menthol', 'INW', 'vape', 'menthol', 0.5, 2.0, 1.0, 0, 0, 'active'),
    ('Milk', 'INW', 'vape', 'cream', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Milk Chocolate', 'INW', 'vape', 'dessert', 1.5, 3.5, 2.5, 14, 0, 'active'),
    ('Natural Tobacco', 'INW', 'vape', 'tobacco', 1.0, 3.0, 2.0, 21, 0, 'active'),
    ('Oak Wood', 'INW', 'vape', 'tobacco', 0.5, 2.0, 1.0, 21, 0, 'active'),
    ('Orange', 'INW', 'vape', 'citrus', 2.0, 4.0, 3.0, 5, 0, 'active'),
    ('Orange Shisha', 'INW', 'vape', 'citrus', 2.0, 4.0, 3.0, 5, 0, 'active'),
    ('Papaya', 'INW', 'vape', 'tropical', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Passion Fruit', 'INW', 'vape', 'tropical', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Peanuts', 'INW', 'vape', 'nuts', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Pear', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Peppermint', 'INW', 'vape', 'menthol', 0.5, 2.0, 1.0, 0, 0, 'active'),
    ('Pineapple', 'INW', 'vape', 'tropical', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Pistachio', 'INW', 'vape', 'nuts', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Plum', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Pomegranate', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Raspberry', 'INW', 'vape', 'berry', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('Rose', 'INW', 'vape', 'fruit', 0.5, 2.0, 1.0, 7, 0, 'active'),
    ('RY4', 'INW', 'vape', 'tobacco', 1.0, 3.0, 2.0, 21, 0, 'active'),
    ('Shisha Strawberry', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 5, 0, 'active'),
    ('Strawberry', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 5, 0, 'active'),
    ('Strawberry Shisha', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 5, 0, 'active'),
    ('Tobacco Absolute', 'INW', 'vape', 'tobacco', 0.5, 2.0, 1.0, 21, 0, 'active'),
    ('Tobacco Gold Ducat', 'INW', 'vape', 'tobacco', 1.0, 3.0, 2.0, 21, 0, 'active'),
    ('Vanilla', 'INW', 'vape', 'cream', 1.5, 3.5, 2.5, 14, 0, 'active'),
    ('Vanilla Shisha', 'INW', 'vape', 'cream', 1.5, 3.5, 2.5, 14, 0, 'active'),
    ('Watermelon', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 5, 0, 'active'),
    ('White Grape', 'INW', 'vape', 'fruit', 2.0, 4.0, 3.0, 7, 0, 'active'),
    ('White Tea', 'INW', 'vape', 'drink', 1.5, 3.5, 2.5, 7, 0, 'active'),
    ('WM', 'INW', 'vape', 'tobacco', 1.0, 3.0, 2.0, 21, 0, 'active'),
    ('Yogurt', 'INW', 'vape', 'cream', 1.5, 3.5, 2.5, 14, 0, 'active')
ON CONFLICT (name, manufacturer_code) DO NOTHING;

-- =====================================================
-- Additional Flavor West Flavors - Comprehensive
-- Source: ATF, community consensus
-- =====================================================

INSERT INTO flavors (name, manufacturer_code, product_type, category, min_percent, max_percent, recommended_percent, steep_days, vg_ratio, status) VALUES
    ('Acai Berry', 'FW', 'vape', 'berry', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Almond', 'FW', 'vape', 'nuts', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Apple Jacks', 'FW', 'vape', 'bakery', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Apple Pie', 'FW', 'vape', 'bakery', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Apricot', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Bacon', 'FW', 'vape', 'other', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Banana', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Banana Split', 'FW', 'vape', 'dessert', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Bavarian Cream', 'FW', 'vape', 'cream', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Blackberry', 'FW', 'vape', 'berry', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Blood Orange', 'FW', 'vape', 'citrus', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Blue Ice', 'FW', 'vape', 'menthol', 2.0, 5.0, 3.0, 0, 0, 'active'),
    ('Blueberry', 'FW', 'vape', 'berry', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Blueberry Graham Waffle', 'FW', 'vape', 'bakery', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Boysenberry', 'FW', 'vape', 'berry', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Brandy', 'FW', 'vape', 'drink', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Brown Sugar', 'FW', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Bubble Gum', 'FW', 'vape', 'candy', 3.0, 7.0, 5.0, 3, 0, 'active'),
    ('Butter Cream', 'FW', 'vape', 'cream', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Butter Pecan', 'FW', 'vape', 'nuts', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Butterscotch', 'FW', 'vape', 'bakery', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Butterscotch Ripple', 'FW', 'vape', 'bakery', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Cake Batter Dip', 'FW', 'vape', 'bakery', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Cantaloupe', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Caramel Apple', 'FW', 'vape', 'bakery', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Caramel Candy', 'FW', 'vape', 'candy', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Cereal Killer', 'FW', 'vape', 'bakery', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Chai Tea', 'FW', 'vape', 'drink', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Cheesecake', 'FW', 'vape', 'dessert', 3.0, 7.0, 5.0, 21, 0, 'active'),
    ('Cherry', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Cherry Balsam', 'FW', 'vape', 'tobacco', 3.0, 7.0, 5.0, 21, 0, 'active'),
    ('Cherry Blast', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Cherry Crush', 'FW', 'vape', 'candy', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Chocolate Mint', 'FW', 'vape', 'dessert', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Cinnamon', 'FW', 'vape', 'spice', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Cinnamon Red Hot', 'FW', 'vape', 'spice', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Citrus Punch', 'FW', 'vape', 'citrus', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Clove', 'FW', 'vape', 'spice', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Coconut', 'FW', 'vape', 'tropical', 2.0, 5.0, 3.0, 7, 0, 'active'),
    ('Coffee', 'FW', 'vape', 'drink', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Cola', 'FW', 'vape', 'drink', 3.0, 7.0, 5.0, 3, 0, 'active'),
    ('Cookie', 'FW', 'vape', 'bakery', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Cookies and Cream', 'FW', 'vape', 'cream', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Cotton Candy', 'FW', 'vape', 'candy', 3.0, 7.0, 5.0, 3, 0, 'active'),
    ('Cranberry', 'FW', 'vape', 'berry', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Cream', 'FW', 'vape', 'cream', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Creme de Menthe', 'FW', 'vape', 'menthol', 2.0, 5.0, 3.0, 0, 0, 'active'),
    ('Cucumber', 'FW', 'vape', 'fruit', 2.0, 5.0, 3.0, 3, 0, 'active'),
    ('Custard', 'FW', 'vape', 'cream', 3.0, 7.0, 5.0, 21, 0, 'active'),
    ('Dragon Fruit', 'FW', 'vape', 'tropical', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Energy Drink', 'FW', 'vape', 'drink', 3.0, 7.0, 5.0, 3, 0, 'active'),
    ('Fig', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('French Vanilla', 'FW', 'vape', 'cream', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Fruit Rings', 'FW', 'vape', 'bakery', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Fruit Stripe Gum', 'FW', 'vape', 'candy', 3.0, 7.0, 5.0, 3, 0, 'active'),
    ('Ginger', 'FW', 'vape', 'spice', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Graham Cracker', 'FW', 'vape', 'bakery', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Grape', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Grape Soda', 'FW', 'vape', 'drink', 3.0, 7.0, 5.0, 3, 0, 'active'),
    ('Grapefruit', 'FW', 'vape', 'citrus', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Gummy Bear', 'FW', 'vape', 'candy', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Hazelnut', 'FW', 'vape', 'nuts', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Honey', 'FW', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Honeydew', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Ice Cream', 'FW', 'vape', 'cream', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Iced Tea', 'FW', 'vape', 'drink', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Key Lime', 'FW', 'vape', 'citrus', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Kiwi', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Lemon', 'FW', 'vape', 'citrus', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Lemon Lime', 'FW', 'vape', 'citrus', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Lemonade', 'FW', 'vape', 'drink', 3.0, 7.0, 5.0, 3, 0, 'active'),
    ('Lime', 'FW', 'vape', 'citrus', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Lychee', 'FW', 'vape', 'tropical', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Macadamia Nut', 'FW', 'vape', 'nuts', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Mango', 'FW', 'vape', 'tropical', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Maple Pecan', 'FW', 'vape', 'bakery', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Maple Syrup', 'FW', 'vape', 'bakery', 2.0, 4.0, 3.0, 14, 0, 'active'),
    ('Marshmallow', 'FW', 'vape', 'candy', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Melon', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Menthol', 'FW', 'vape', 'menthol', 1.0, 3.0, 2.0, 0, 0, 'active'),
    ('Milk Chocolate', 'FW', 'vape', 'dessert', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Mocha', 'FW', 'vape', 'drink', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Natural Strawberry', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Nectarine', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Orange', 'FW', 'vape', 'citrus', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Orange Cream', 'FW', 'vape', 'cream', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Papaya', 'FW', 'vape', 'tropical', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Passion Fruit', 'FW', 'vape', 'tropical', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Peach', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Peanut Butter', 'FW', 'vape', 'nuts', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Pear', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Pecan', 'FW', 'vape', 'nuts', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Peppermint', 'FW', 'vape', 'menthol', 1.0, 3.0, 2.0, 0, 0, 'active'),
    ('Pina Colada', 'FW', 'vape', 'drink', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Pineapple', 'FW', 'vape', 'tropical', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Pistachio', 'FW', 'vape', 'nuts', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Plum', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Pomegranate', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Rainbow Sherbet', 'FW', 'vape', 'cream', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Raisin', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Raspberry', 'FW', 'vape', 'berry', 3.0, 7.0, 5.0, 7, 0, 'active'),
    ('Red Cinnamon', 'FW', 'vape', 'spice', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Red Licorice', 'FW', 'vape', 'candy', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Root Beer', 'FW', 'vape', 'drink', 3.0, 7.0, 5.0, 3, 0, 'active'),
    ('Rum', 'FW', 'vape', 'drink', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('RY4', 'FW', 'vape', 'tobacco', 3.0, 7.0, 5.0, 21, 0, 'active'),
    ('Salted Caramel', 'FW', 'vape', 'bakery', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Snickerdoodle', 'FW', 'vape', 'bakery', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Spearmint', 'FW', 'vape', 'menthol', 1.0, 3.0, 2.0, 0, 0, 'active'),
    ('Strawberry', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Strawberry Cheesecake', 'FW', 'vape', 'dessert', 3.0, 7.0, 5.0, 21, 0, 'active'),
    ('Strawberry Shortcake', 'FW', 'vape', 'bakery', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Sweet Cream', 'FW', 'vape', 'cream', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Sweetener', 'FW', 'vape', 'other', 0.5, 2.0, 1.0, 0, 0, 'active'),
    ('Tangerine', 'FW', 'vape', 'citrus', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Tobacco', 'FW', 'vape', 'tobacco', 3.0, 7.0, 5.0, 21, 0, 'active'),
    ('Tres Leches', 'FW', 'vape', 'cream', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Tropical Punch', 'FW', 'vape', 'drink', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Vanilla', 'FW', 'vape', 'cream', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Vanilla Bean Ice Cream', 'FW', 'vape', 'cream', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Vanilla Cupcake', 'FW', 'vape', 'bakery', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Waffle', 'FW', 'vape', 'bakery', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Walnut', 'FW', 'vape', 'nuts', 2.0, 5.0, 3.0, 14, 0, 'active'),
    ('Watermelon', 'FW', 'vape', 'fruit', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Watermelon Candy', 'FW', 'vape', 'candy', 3.0, 7.0, 5.0, 5, 0, 'active'),
    ('Wintergreen', 'FW', 'vape', 'menthol', 1.0, 3.0, 2.0, 0, 0, 'active'),
    ('Yellow Cake', 'FW', 'vape', 'bakery', 3.0, 7.0, 5.0, 14, 0, 'active'),
    ('Yogurt', 'FW', 'vape', 'cream', 2.0, 5.0, 3.0, 14, 0, 'active')
ON CONFLICT (name, manufacturer_code) DO NOTHING;

-- =====================================================
-- Additional Flavorah Flavors - Comprehensive
-- Source: ATF, community consensus
-- =====================================================

INSERT INTO flavors (name, manufacturer_code, product_type, category, min_percent, max_percent, recommended_percent, steep_days, vg_ratio, status) VALUES
    ('Aged Bourbon', 'FLV', 'vape', 'drink', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Almond', 'FLV', 'vape', 'nuts', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Alpine Strawberry', 'FLV', 'vape', 'fruit', 0.75, 2.0, 1.25, 5, 0, 'active'),
    ('Apple', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Apple Cider', 'FLV', 'vape', 'drink', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Apple Cranberry', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Apple Filling', 'FLV', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Apricot', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Banana', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Banana Flambé', 'FLV', 'vape', 'dessert', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Beer Nuts', 'FLV', 'vape', 'nuts', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Betelnut', 'FLV', 'vape', 'tobacco', 0.5, 2.0, 1.0, 21, 0, 'active'),
    ('Biscotti', 'FLV', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Blackberry', 'FLV', 'vape', 'berry', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Blueberry', 'FLV', 'vape', 'berry', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Blueberry Muffin', 'FLV', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Boysenberry', 'FLV', 'vape', 'berry', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Bread', 'FLV', 'vape', 'bakery', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Brown Sugar', 'FLV', 'vape', 'bakery', 0.25, 1.0, 0.5, 14, 0, 'active'),
    ('Butterscotch', 'FLV', 'vape', 'bakery', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Cantaloupe', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Caramel', 'FLV', 'vape', 'bakery', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Cherimoya', 'FLV', 'vape', 'tropical', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Cherry', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Cherry Blossom', 'FLV', 'vape', 'fruit', 0.5, 2.0, 1.0, 7, 0, 'active'),
    ('Chocolate Deutsch', 'FLV', 'vape', 'dessert', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Cinnamon Crunch', 'FLV', 'vape', 'bakery', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Citrus Soda', 'FLV', 'vape', 'drink', 1.0, 3.0, 2.0, 3, 0, 'active'),
    ('Clove', 'FLV', 'vape', 'spice', 0.25, 1.0, 0.5, 14, 0, 'active'),
    ('Coconut', 'FLV', 'vape', 'tropical', 0.5, 2.0, 1.0, 7, 0, 'active'),
    ('Coffee', 'FLV', 'vape', 'drink', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Cookie', 'FLV', 'vape', 'bakery', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Cookie Dough', 'FLV', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Cotton Candy', 'FLV', 'vape', 'candy', 0.5, 2.0, 1.0, 3, 0, 'active'),
    ('Cranberry', 'FLV', 'vape', 'berry', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Cream', 'FLV', 'vape', 'cream', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Creme de Menthe', 'FLV', 'vape', 'menthol', 0.5, 2.0, 1.0, 0, 0, 'active'),
    ('Cupcake Batter', 'FLV', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Cured Tobacco', 'FLV', 'vape', 'tobacco', 0.5, 2.0, 1.0, 21, 0, 'active'),
    ('Custard', 'FLV', 'vape', 'cream', 0.5, 2.0, 1.0, 21, 0, 'active'),
    ('Divinity', 'FLV', 'vape', 'candy', 0.5, 2.0, 1.0, 7, 0, 'active'),
    ('Dragonfruit', 'FLV', 'vape', 'tropical', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Egg Nog', 'FLV', 'vape', 'cream', 1.0, 3.0, 2.0, 21, 0, 'active'),
    ('Elderflower', 'FLV', 'vape', 'fruit', 0.5, 2.0, 1.0, 7, 0, 'active'),
    ('Eucalyptus', 'FLV', 'vape', 'menthol', 0.25, 1.0, 0.5, 0, 0, 'active'),
    ('Fig', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Frosting', 'FLV', 'vape', 'bakery', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Fruit Punch', 'FLV', 'vape', 'drink', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Ginger', 'FLV', 'vape', 'spice', 0.25, 1.0, 0.5, 14, 0, 'active'),
    ('Ginger Snap', 'FLV', 'vape', 'bakery', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Graham Cracker', 'FLV', 'vape', 'bakery', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Grape', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Grapefruit', 'FLV', 'vape', 'citrus', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Granny Smith Apple', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Greek Yogurt', 'FLV', 'vape', 'cream', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Guava', 'FLV', 'vape', 'tropical', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Heat', 'FLV', 'vape', 'spice', 0.1, 0.5, 0.25, 14, 0, 'active'),
    ('Hibiscus', 'FLV', 'vape', 'fruit', 0.5, 2.0, 1.0, 7, 0, 'active'),
    ('Honey', 'FLV', 'vape', 'bakery', 0.25, 1.0, 0.5, 14, 0, 'active'),
    ('Honeydew', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Irish Cream', 'FLV', 'vape', 'drink', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Jackfruit', 'FLV', 'vape', 'tropical', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Jammy Berry', 'FLV', 'vape', 'berry', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Kiwi', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Lemon', 'FLV', 'vape', 'citrus', 0.5, 2.0, 1.0, 5, 0, 'active'),
    ('Lemon Tea', 'FLV', 'vape', 'drink', 0.5, 2.0, 1.0, 7, 0, 'active'),
    ('Lemonade', 'FLV', 'vape', 'drink', 1.0, 3.0, 2.0, 3, 0, 'active'),
    ('Lime', 'FLV', 'vape', 'citrus', 0.5, 2.0, 1.0, 5, 0, 'active'),
    ('Lychee', 'FLV', 'vape', 'tropical', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Mango', 'FLV', 'vape', 'tropical', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Maple Bar', 'FLV', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Marshmallow', 'FLV', 'vape', 'candy', 0.5, 2.0, 1.0, 7, 0, 'active'),
    ('Marshmallow Vanilla', 'FLV', 'vape', 'cream', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Melon Rind', 'FLV', 'vape', 'fruit', 0.5, 2.0, 1.0, 5, 0, 'active'),
    ('Milk and Honey', 'FLV', 'vape', 'cream', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Milk Chocolate', 'FLV', 'vape', 'dessert', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Moscato', 'FLV', 'vape', 'drink', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Mulled Wine', 'FLV', 'vape', 'drink', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Native Tobacco', 'FLV', 'vape', 'tobacco', 0.5, 2.0, 1.0, 21, 0, 'active'),
    ('Nectarine', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Orange', 'FLV', 'vape', 'citrus', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Orange Citrus', 'FLV', 'vape', 'citrus', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Papaya Punch', 'FLV', 'vape', 'tropical', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Passion Fruit', 'FLV', 'vape', 'tropical', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Peach', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Peanut Butter', 'FLV', 'vape', 'nuts', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Pear', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Persimmon', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Pineapple', 'FLV', 'vape', 'tropical', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Pink Guava', 'FLV', 'vape', 'tropical', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Pistachio', 'FLV', 'vape', 'nuts', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Plum', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Popcorn', 'FLV', 'vape', 'bakery', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Pound Cake', 'FLV', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Praline', 'FLV', 'vape', 'bakery', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Pumpkin', 'FLV', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Pumpkin Spice', 'FLV', 'vape', 'spice', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Raspberry', 'FLV', 'vape', 'berry', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Red Cinnamon', 'FLV', 'vape', 'spice', 0.25, 1.0, 0.5, 14, 0, 'active'),
    ('Rich Cinnamon', 'FLV', 'vape', 'spice', 0.25, 1.0, 0.5, 14, 0, 'active'),
    ('Root Beer', 'FLV', 'vape', 'drink', 1.0, 3.0, 2.0, 3, 0, 'active'),
    ('Rose Essence', 'FLV', 'vape', 'fruit', 0.25, 1.0, 0.5, 7, 0, 'active'),
    ('Smooth Vanilla', 'FLV', 'vape', 'cream', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Smore', 'FLV', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Sour Apple', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Spearmint', 'FLV', 'vape', 'menthol', 0.25, 1.0, 0.5, 0, 0, 'active'),
    ('Star Fruit', 'FLV', 'vape', 'tropical', 1.0, 3.0, 2.0, 7, 0, 'active'),
    ('Strawberry', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Strawberry Filling', 'FLV', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Strawberry Smash', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Sweet Coconut', 'FLV', 'vape', 'tropical', 0.5, 2.0, 1.0, 7, 0, 'active'),
    ('Sweetness', 'FLV', 'vape', 'other', 0.25, 1.0, 0.5, 0, 0, 'active'),
    ('Tangerine', 'FLV', 'vape', 'citrus', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Tatanka', 'FLV', 'vape', 'tobacco', 0.5, 2.0, 1.0, 21, 0, 'active'),
    ('Thai Chai', 'FLV', 'vape', 'drink', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Tropical Punch', 'FLV', 'vape', 'drink', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Vanilla Bean', 'FLV', 'vape', 'cream', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Vanilla Custard', 'FLV', 'vape', 'cream', 0.5, 2.0, 1.0, 21, 0, 'active'),
    ('Vanilla Pudding', 'FLV', 'vape', 'cream', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Virginia Tobacco', 'FLV', 'vape', 'tobacco', 0.5, 2.0, 1.0, 21, 0, 'active'),
    ('Waffle', 'FLV', 'vape', 'bakery', 1.0, 3.0, 2.0, 14, 0, 'active'),
    ('Watermelon', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Watermelon Candy', 'FLV', 'vape', 'candy', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('White Chocolate', 'FLV', 'vape', 'dessert', 0.5, 2.0, 1.0, 14, 0, 'active'),
    ('Wild Melon', 'FLV', 'vape', 'fruit', 1.0, 3.0, 2.0, 5, 0, 'active'),
    ('Wintergreen', 'FLV', 'vape', 'menthol', 0.25, 1.0, 0.5, 0, 0, 'active'),
    ('Yakima Hops', 'FLV', 'vape', 'drink', 0.5, 2.0, 1.0, 14, 0, 'active')
ON CONFLICT (name, manufacturer_code) DO NOTHING;

-- =====================================================
-- Additional Shisha Flavors - Al Fakher (ALF)
-- Source: Community consensus, hookah forums
-- =====================================================

INSERT INTO flavors (name, manufacturer_code, product_type, category, min_percent, max_percent, recommended_percent, steep_days, vg_ratio, status) VALUES
    ('Blueberry Mint', 'ALF', 'shisha', 'berry', NULL, NULL, NULL, 0, 0, 'active'),
    ('Cherry Mint', 'ALF', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Citrus Mint', 'ALF', 'shisha', 'citrus', NULL, NULL, NULL, 0, 0, 'active'),
    ('Coconut', 'ALF', 'shisha', 'tropical', NULL, NULL, NULL, 0, 0, 'active'),
    ('Coffee', 'ALF', 'shisha', 'drink', NULL, NULL, NULL, 0, 0, 'active'),
    ('Cream', 'ALF', 'shisha', 'cream', NULL, NULL, NULL, 0, 0, 'active'),
    ('Cucumber', 'ALF', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Double Apple Mint', 'ALF', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Grapefruit', 'ALF', 'shisha', 'citrus', NULL, NULL, NULL, 0, 0, 'active'),
    ('Grapefruit Mint', 'ALF', 'shisha', 'citrus', NULL, NULL, NULL, 0, 0, 'active'),
    ('Guava', 'ALF', 'shisha', 'tropical', NULL, NULL, NULL, 0, 0, 'active'),
    ('Kiwi', 'ALF', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Lemon Mint', 'ALF', 'shisha', 'citrus', NULL, NULL, NULL, 0, 0, 'active'),
    ('Mango', 'ALF', 'shisha', 'tropical', NULL, NULL, NULL, 0, 0, 'active'),
    ('Mixed Fruit', 'ALF', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Orange Mint', 'ALF', 'shisha', 'citrus', NULL, NULL, NULL, 0, 0, 'active'),
    ('Peach', 'ALF', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Raspberry', 'ALF', 'shisha', 'berry', NULL, NULL, NULL, 0, 0, 'active'),
    ('Rose', 'ALF', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Strawberry Banana', 'ALF', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Vanilla', 'ALF', 'shisha', 'cream', NULL, NULL, NULL, 0, 0, 'active'),
    ('Watermelon Mint', 'ALF', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active')
ON CONFLICT (name, manufacturer_code) DO NOTHING;

-- =====================================================
-- Additional Shisha Flavors - Nakhla (NAK)
-- Source: Community consensus, hookah forums
-- =====================================================

INSERT INTO flavors (name, manufacturer_code, product_type, category, min_percent, max_percent, recommended_percent, steep_days, vg_ratio, status) VALUES
    ('Apple', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Apricot', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Banana', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Cardamom', 'NAK', 'shisha', 'spice', NULL, NULL, NULL, 0, 0, 'active'),
    ('Cherry', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Cinnamon', 'NAK', 'shisha', 'spice', NULL, NULL, NULL, 0, 0, 'active'),
    ('Coconut', 'NAK', 'shisha', 'tropical', NULL, NULL, NULL, 0, 0, 'active'),
    ('Cola', 'NAK', 'shisha', 'drink', NULL, NULL, NULL, 0, 0, 'active'),
    ('Double Apple', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Earl Grey', 'NAK', 'shisha', 'drink', NULL, NULL, NULL, 0, 0, 'active'),
    ('Grape', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Grapefruit', 'NAK', 'shisha', 'citrus', NULL, NULL, NULL, 0, 0, 'active'),
    ('Ice Apple', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Ice Grape Mint', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Ice Lemon Mint', 'NAK', 'shisha', 'citrus', NULL, NULL, NULL, 0, 0, 'active'),
    ('Ice Watermelon Mint', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Lemon', 'NAK', 'shisha', 'citrus', NULL, NULL, NULL, 0, 0, 'active'),
    ('Mango', 'NAK', 'shisha', 'tropical', NULL, NULL, NULL, 0, 0, 'active'),
    ('Melon', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Mint', 'NAK', 'shisha', 'menthol', NULL, NULL, NULL, 0, 0, 'active'),
    ('Orange', 'NAK', 'shisha', 'citrus', NULL, NULL, NULL, 0, 0, 'active'),
    ('Peach', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Pineapple', 'NAK', 'shisha', 'tropical', NULL, NULL, NULL, 0, 0, 'active'),
    ('Rose', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Strawberry', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Sweet Melon', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Two Apples', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active'),
    ('Watermelon', 'NAK', 'shisha', 'fruit', NULL, NULL, NULL, 0, 0, 'active')
ON CONFLICT (name, manufacturer_code) DO NOTHING;

-- =====================================================
-- VERIFICATION QUERY - Phase 4
-- =====================================================
DO $$
DECLARE
    total_count INT;
    tpa_count INT;
    inw_count INT;
    fw_count INT;
    flv_count INT;
    alf_count INT;
    nak_count INT;
BEGIN
    SELECT COUNT(*) INTO total_count FROM flavors WHERE status = 'active';
    SELECT COUNT(*) INTO tpa_count FROM flavors WHERE manufacturer_code = 'TPA' AND status = 'active';
    SELECT COUNT(*) INTO inw_count FROM flavors WHERE manufacturer_code = 'INW' AND status = 'active';
    SELECT COUNT(*) INTO fw_count FROM flavors WHERE manufacturer_code = 'FW' AND status = 'active';
    SELECT COUNT(*) INTO flv_count FROM flavors WHERE manufacturer_code = 'FLV' AND status = 'active';
    SELECT COUNT(*) INTO alf_count FROM flavors WHERE manufacturer_code = 'ALF' AND status = 'active';
    SELECT COUNT(*) INTO nak_count FROM flavors WHERE manufacturer_code = 'NAK' AND status = 'active';
    
    RAISE NOTICE '=== FLAVOR DATABASE EXPANSION PHASE 4 COMPLETE ===';
    RAISE NOTICE 'Total active flavors: %', total_count;
    RAISE NOTICE 'TPA: %', tpa_count;
    RAISE NOTICE 'Inawera (INW): %', inw_count;
    RAISE NOTICE 'Flavor West (FW): %', fw_count;
    RAISE NOTICE 'Flavorah (FLV): %', flv_count;
    RAISE NOTICE 'Al Fakher (ALF): %', alf_count;
    RAISE NOTICE 'Nakhla (NAK): %', nak_count;
END $$;
