-- =============================================
-- Email translations for N8N workflows
-- UTF-8 safe - stored in Supabase, read by N8N Code nodes
-- Řeší problém s diakritikou v N8N Code nodech
-- 06.03.2026
-- =============================================

CREATE TABLE IF NOT EXISTS email_translations (
  id serial PRIMARY KEY,
  template_key text NOT NULL,
  lang text NOT NULL,
  greeting text NOT NULL,
  body text NOT NULL,
  sign_off text NOT NULL,
  subject_tpl text,
  extra jsonb,
  UNIQUE(template_key, lang)
);

COMMENT ON TABLE email_translations IS 'Email překlady pro N8N WF1/WF3/WF6 — UTF-8';

-- =============================================
-- WF1: Bug report acknowledgment emails
-- =============================================
INSERT INTO email_translations (template_key, lang, greeting, body, sign_off) VALUES
('bug', 'cs', 'Dobrý den,', 'Děkujeme za nahlášení chyby v aplikaci LiquiMixer. Váš podnět jsme zaznamenali a náš tým se jím bude zabývat. Oprava bude součástí některé z nadcházejících aktualizací.', 'S pozdravem,'),
('bug', 'sk', 'Dobrý deň,', 'Ďakujeme za nahlásenie chyby v aplikácii LiquiMixer. Váš podnet sme zaznamenali a náš tím sa ním bude zaoberať. Oprava bude súčasťou niektorej z nadchádzajúcich aktualizácií.', 'S pozdravom,'),
('bug', 'en', 'Hello,', 'Thank you for reporting a bug in LiquiMixer. We have recorded your report and our team will look into it. The fix will be included in an upcoming update.', 'Best regards,'),
('bug', 'de', 'Hallo,', 'Vielen Dank für die Meldung eines Fehlers in LiquiMixer. Wir haben Ihren Bericht aufgenommen und unser Team wird sich darum kümmern. Die Behebung wird in einem kommenden Update enthalten sein.', 'Mit freundlichen Grüßen,'),
('bug', 'fr', 'Bonjour,', 'Merci d''avoir signalé un bug dans LiquiMixer. Nous avons enregistré votre rapport et notre équipe s''en occupera. La correction sera incluse dans une prochaine mise à jour.', 'Cordialement,'),
('bug', 'es', 'Hola,', 'Gracias por reportar un error en LiquiMixer. Hemos registrado su informe y nuestro equipo lo investigará. La corrección se incluirá en una próxima actualización.', 'Atentamente,'),
('bug', 'it', 'Salve,', 'Grazie per aver segnalato un bug in LiquiMixer. Abbiamo registrato la sua segnalazione e il nostro team se ne occuperà. La correzione sarà inclusa in un prossimo aggiornamento.', 'Cordiali saluti,'),
('bug', 'pt', 'Olá,', 'Obrigado por reportar um bug no LiquiMixer. Registramos seu relatório e nossa equipe irá investigá-lo. A correção será incluída em uma próxima atualização.', 'Atenciosamente,'),
('bug', 'pl', 'Dzień dobry,', 'Dziękujemy za zgłoszenie błędu w LiquiMixer. Zarejestrowaliśmy Państwa zgłoszenie i nasz zespół się nim zajmie. Poprawka zostanie uwzględniona w jednej z nadchodzących aktualizacji.', 'Z poważaniem,'),
('bug', 'nl', 'Hallo,', 'Bedankt voor het melden van een bug in LiquiMixer. We hebben uw melding geregistreerd en ons team zal ernaar kijken. De fix wordt opgenomen in een komende update.', 'Met vriendelijke groet,'),
('bug', 'ru', 'Здравствуйте,', 'Спасибо за сообщение об ошибке в LiquiMixer. Мы зафиксировали ваш отчёт и наша команда разберётся с ним. Исправление будет включено в одно из ближайших обновлений.', 'С уважением,'),
('bug', 'uk', 'Доброго дня,', 'Дякуємо за повідомлення про помилку в LiquiMixer. Ми зареєстрували ваш звіт і наша команда його розгляне. Виправлення буде включене в одне з наступних оновлень.', 'З повагою,'),
('bug', 'hu', 'Tisztelt Felhasználó,', 'Köszönjük, hogy jelezte a hibát a LiquiMixerben. Rögzítettük bejelentését és csapatunk foglalkozni fog vele. A javítás a következő frissítések egyikében lesz elérhető.', 'Tisztelettel,'),
('bug', 'ro', 'Bună ziua,', 'Vă mulțumim pentru raportarea unui bug în LiquiMixer. Am înregistrat raportul dumneavoastră și echipa noastră se va ocupa de el. Remedierea va fi inclusă într-o actualizare viitoare.', 'Cu stimă,'),
('bug', 'tr', 'Merhaba,', 'LiquiMixer''deki bir hatayı bildirdiğiniz için teşekkür ederiz. Raporunuzu kaydettik ve ekibimiz bununla ilgilenecektir. Düzeltme yaklaşan güncellemelerden birinde yer alacaktır.', 'Saygılarımla,'),
('bug', 'sv', 'Hej,', 'Tack för att du rapporterade en bugg i LiquiMixer. Vi har registrerat din rapport och vårt team kommer att titta på det. Rättningen kommer att inkluderas i en kommande uppdatering.', 'Med vänliga hälsningar,'),
('bug', 'da', 'Hej,', 'Tak fordi du rapporterede en fejl i LiquiMixer. Vi har registreret din rapport og vores team vil se på det. Rettelsen vil blive inkluderet i en kommende opdatering.', 'Med venlig hilsen,'),
('bug', 'fi', 'Hei,', 'Kiitos LiquiMixerin virheen ilmoittamisesta. Olemme kirjanneet raporttisi ja tiimimme tutkii asiaa. Korjaus sisällytetään tulevaan päivitykseen.', 'Ystävällisesti,'),
('bug', 'no', 'Hei,', 'Takk for at du rapporterte en feil i LiquiMixer. Vi har registrert rapporten din og teamet vårt vil se på det. Rettelsen vil bli inkludert i en kommende oppdatering.', 'Med vennlig hilsen,'),
('bug', 'hr', 'Poštovani,', 'Hvala vam na prijavi greške u LiquiMixeru. Zabilježili smo vaš izvještaj i naš tim će se time pozabaviti. Popravak će biti uključen u jedno od nadolazećih ažuriranja.', 'S poštovanjem,'),
('bug', 'sr', 'Poštovani,', 'Hvala vam na prijavi greške u LiquiMixeru. Zabeležili smo vaš izveštaj i naš tim će se time pozabaviti. Popravka će biti uključena u jedno od nadolazećih ažuriranja.', 'S poštovanjem,'),
('bug', 'bg', 'Здравейте,', 'Благодарим ви за докладването на грешка в LiquiMixer. Регистрирахме вашия доклад и нашият екип ще се заеме с него. Поправката ще бъде включена в едно от предстоящите обновления.', 'С уважение,'),
('bug', 'el', 'Γεια σας,', 'Ευχαριστούμε που αναφέρατε ένα σφάλμα στο LiquiMixer. Καταγράψαμε την αναφορά σας και η ομάδα μας θα το εξετάσει. Η διόρθωση θα συμπεριληφθεί σε μια επερχόμενη ενημέρωση.', 'Με εκτίμηση,'),
('bug', 'lt', 'Gerbiamas vartotojau,', 'Dėkojame už pranešimą apie klaidą LiquiMixer programoje. Užregistravome jūsų pranešimą ir mūsų komanda jį išnagrinės. Taisymas bus įtrauktas į vieną iš būsimų atnaujinimų.', 'Pagarbiai,'),
('bug', 'lv', 'Cienījamais lietotāj,', 'Paldies par kļūdas ziņošanu LiquiMixer lietotnē. Esam reģistrējuši jūsu ziņojumu un mūsu komanda to izskatīs. Labojums tiks iekļauts kādā no nākamajiem atjauninājumiem.', 'Ar cieņu,'),
('bug', 'et', 'Lugupeetud kasutaja,', 'Täname, et teatasite LiquiMixeri veast. Oleme teie teate registreerinud ja meie meeskond uurib seda. Parandus lisatakse ühte tulevastest värskendustest.', 'Lugupidamisega,'),
('bug', 'ja', 'こんにちは、', 'LiquiMixerのバグをご報告いただきありがとうございます。お客様のレポートを記録し、チームが対応いたします。修正は今後のアップデートに含まれます。', '敬具、'),
('bug', 'ko', '안녕하세요,', 'LiquiMixer의 버그를 신고해 주셔서 감사합니다. 귀하의 보고서를 기록했으며 저희 팀이 검토할 것입니다. 수정 사항은 다음 업데이트에 포함될 예정입니다.', '감사합니다,'),
('bug', 'zh-CN', '您好，', '感谢您报告LiquiMixer中的错误。我们已记录您的报告，我们的团队将对其进行调查。修复将包含在即将发布的更新中。', '此致敬礼，'),
('bug', 'ar', 'مرحباً،', 'شكراً لإبلاغكم عن خطأ في LiquiMixer. لقد سجلنا تقريركم وسيقوم فريقنا بمراجعته. سيتم تضمين الإصلاح في تحديث قادم.', 'مع التحيات،')
ON CONFLICT (template_key, lang) DO UPDATE SET greeting=EXCLUDED.greeting, body=EXCLUDED.body, sign_off=EXCLUDED.sign_off;

-- =============================================
-- WF3: GDPR deletion confirmation emails
-- =============================================
INSERT INTO email_translations (template_key, lang, greeting, body, sign_off, subject_tpl, extra) VALUES
('gdpr', 'cs', 'Dobrý den,', 'Obdrželi jsme Vaši žádost o smazání účtu v aplikaci LiquiMixer.', 'S pozdravem,', 'LiquiMixer - Potvrzení smazání účtu', '{"warning":"Upozorňujeme, že všechna Vaše data budou trvale smazána, včetně receptur, produktů, nastavení a osobních údajů.","irreversible":"Tato akce je NEVRATNÁ.","delete_btn":"SMAZAT MŮJ ÚČET","cancel_btn":"ZRUŠIT ŽÁDOST","expiry":"Odkazy jsou platné 24 hodin.","ignore":"Pokud jste tuto žádost nepodali, můžete tento email ignorovat."}'::jsonb),
('gdpr', 'sk', 'Dobrý deň,', 'Prijali sme Vašu žiadosť o vymazanie účtu v aplikácii LiquiMixer.', 'S pozdravom,', 'LiquiMixer - Potvrdenie vymazania účtu', '{"warning":"Upozorňujeme, že všetky Vaše údaje budú trvalo vymazané, vrátane receptúr, produktov, nastavení a osobných údajov.","irreversible":"Táto akcia je NEVRATNÁ.","delete_btn":"VYMAZAŤ MÔJ ÚČET","cancel_btn":"ZRUŠIŤ ŽIADOSŤ","expiry":"Odkazy sú platné 24 hodín.","ignore":"Ak ste túto žiadosť nepodali, môžete tento email ignorovať."}'::jsonb),
('gdpr', 'en', 'Hello,', 'We have received your request to delete your LiquiMixer account.', 'Best regards,', 'LiquiMixer - Account Deletion Confirmation', '{"warning":"Please note that all your data will be permanently deleted, including recipes, products, settings and personal data.","irreversible":"This action is IRREVERSIBLE.","delete_btn":"DELETE MY ACCOUNT","cancel_btn":"CANCEL REQUEST","expiry":"Links are valid for 24 hours.","ignore":"If you did not submit this request, you can ignore this email."}'::jsonb),
('gdpr', 'de', 'Hallo,', 'Wir haben Ihre Anfrage zur Löschung Ihres LiquiMixer-Kontos erhalten.', 'Mit freundlichen Grüßen,', 'LiquiMixer - Bestätigung der Kontolöschung', '{"warning":"Bitte beachten Sie, dass alle Ihre Daten dauerhaft gelöscht werden, einschließlich Rezepturen, Produkte, Einstellungen und persönliche Daten.","irreversible":"Diese Aktion ist UNWIDERRUFLICH.","delete_btn":"MEIN KONTO LÖSCHEN","cancel_btn":"ANFRAGE STORNIEREN","expiry":"Die Links sind 24 Stunden gültig.","ignore":"Wenn Sie diese Anfrage nicht gestellt haben, können Sie diese E-Mail ignorieren."}'::jsonb),
('gdpr', 'fr', 'Bonjour,', 'Nous avons reçu votre demande de suppression de votre compte LiquiMixer.', 'Cordialement,', 'LiquiMixer - Confirmation de suppression de compte', '{"warning":"Veuillez noter que toutes vos données seront définitivement supprimées, y compris les recettes, produits, paramètres et données personnelles.","irreversible":"Cette action est IRRÉVERSIBLE.","delete_btn":"SUPPRIMER MON COMPTE","cancel_btn":"ANNULER LA DEMANDE","expiry":"Les liens sont valables 24 heures.","ignore":"Si vous n''avez pas soumis cette demande, vous pouvez ignorer cet email."}'::jsonb),
('gdpr', 'es', 'Hola,', 'Hemos recibido su solicitud para eliminar su cuenta de LiquiMixer.', 'Atentamente,', 'LiquiMixer - Confirmación de eliminación de cuenta', '{"warning":"Tenga en cuenta que todos sus datos serán eliminados permanentemente, incluyendo recetas, productos, configuraciones y datos personales.","irreversible":"Esta acción es IRREVERSIBLE.","delete_btn":"ELIMINAR MI CUENTA","cancel_btn":"CANCELAR SOLICITUD","expiry":"Los enlaces son válidos por 24 horas.","ignore":"Si no realizó esta solicitud, puede ignorar este correo."}'::jsonb),
('gdpr', 'it', 'Salve,', 'Abbiamo ricevuto la sua richiesta di eliminazione dell''account LiquiMixer.', 'Cordiali saluti,', 'LiquiMixer - Conferma eliminazione account', '{"warning":"Si prega di notare che tutti i suoi dati saranno eliminati permanentemente, incluse ricette, prodotti, impostazioni e dati personali.","irreversible":"Questa azione è IRREVERSIBILE.","delete_btn":"ELIMINA IL MIO ACCOUNT","cancel_btn":"ANNULLA RICHIESTA","expiry":"I link sono validi per 24 ore.","ignore":"Se non ha inoltrato questa richiesta, può ignorare questa email."}'::jsonb),
('gdpr', 'pt', 'Olá,', 'Recebemos seu pedido de exclusão da sua conta LiquiMixer.', 'Atenciosamente,', 'LiquiMixer - Confirmação de exclusão de conta', '{"warning":"Observe que todos os seus dados serão excluídos permanentemente, incluindo receitas, produtos, configurações e dados pessoais.","irreversible":"Esta ação é IRREVERSÍVEL.","delete_btn":"EXCLUIR MINHA CONTA","cancel_btn":"CANCELAR PEDIDO","expiry":"Os links são válidos por 24 horas.","ignore":"Se você não fez este pedido, pode ignorar este email."}'::jsonb),
('gdpr', 'pl', 'Dzień dobry,', 'Otrzymaliśmy Państwa żądanie usunięcia konta LiquiMixer.', 'Z poważaniem,', 'LiquiMixer - Potwierdzenie usunięcia konta', '{"warning":"Informujemy, że wszystkie Państwa dane zostaną trwale usunięte, w tym receptury, produkty, ustawienia i dane osobowe.","irreversible":"Ta czynność jest NIEODWRACALNA.","delete_btn":"USUŃ MOJE KONTO","cancel_btn":"ANULUJ ŻĄDANIE","expiry":"Linki są ważne przez 24 godziny.","ignore":"Jeśli nie złożyli Państwo tego żądania, mogą Państwo zignorować tę wiadomość."}'::jsonb),
('gdpr', 'nl', 'Hallo,', 'We hebben uw verzoek om uw LiquiMixer-account te verwijderen ontvangen.', 'Met vriendelijke groet,', 'LiquiMixer - Bevestiging accountverwijdering', '{"warning":"Houd er rekening mee dat al uw gegevens permanent worden verwijderd, inclusief recepten, producten, instellingen en persoonlijke gegevens.","irreversible":"Deze actie is ONOMKEERBAAR.","delete_btn":"VERWIJDER MIJN ACCOUNT","cancel_btn":"ANNULEER VERZOEK","expiry":"De links zijn 24 uur geldig.","ignore":"Als u dit verzoek niet heeft ingediend, kunt u deze e-mail negeren."}'::jsonb),
('gdpr', 'tr', 'Merhaba,', 'LiquiMixer hesabınızı silme talebinizi aldık.', 'Saygılarımla,', 'LiquiMixer - Hesap silme onayı', '{"warning":"Tüm verilerinizin kalıcı olarak silineceğini lütfen unutmayın; tarifler, ürünler, ayarlar ve kişisel veriler dahil.","irreversible":"Bu işlem GERİ ALINAMAZ.","delete_btn":"HESABIMI SİL","cancel_btn":"TALEBİ İPTAL ET","expiry":"Bağlantılar 24 saat geçerlidir.","ignore":"Bu talebi siz yapmadıysanız, bu e-postayı göz ardı edebilirsiniz."}'::jsonb),
('gdpr', 'hu', 'Tisztelt Felhasználó,', 'Megkaptuk a LiquiMixer fiókja törlésére vonatkozó kérelmét.', 'Tisztelettel,', 'LiquiMixer - Fiók törlés megerősítése', '{"warning":"Kérjük, vegye figyelembe, hogy minden adata véglegesen törlésre kerül, beleértve a receptúrákat, termékeket, beállításokat és személyes adatokat.","irreversible":"Ez a művelet VISSZAVONHATATLAN.","delete_btn":"FIÓKOM TÖRLÉSE","cancel_btn":"KÉRELEM VISSZAVONÁSA","expiry":"A linkek 24 óráig érvényesek.","ignore":"Ha nem Ön nyújtotta be ezt a kérelmet, hagyja figyelmen kívül."}'::jsonb),
('gdpr', 'ro', 'Bună ziua,', 'Am primit solicitarea de ștergere a contului LiquiMixer.', 'Cu stimă,', 'LiquiMixer - Confirmare ștergere cont', '{"warning":"Toate datele vor fi șterse permanent, inclusiv rețetele, produsele, setările și datele personale.","irreversible":"Această acțiune este IREVERSIBILĂ.","delete_btn":"ȘTERGE CONTUL MEU","cancel_btn":"ANULEAZĂ SOLICITAREA","expiry":"Link-urile expiră în 24 de ore.","ignore":"Dacă nu ați făcut această solicitare, puteți ignora acest email."}'::jsonb),
('gdpr', 'ru', 'Здравствуйте,', 'Мы получили ваш запрос на удаление аккаунта LiquiMixer.', 'С уважением,', 'LiquiMixer - Подтверждение удаления аккаунта', '{"warning":"Обратите внимание, что все ваши данные будут безвозвратно удалены, включая рецептуры, продукты, настройки и персональные данные.","irreversible":"Это действие НЕОБРАТИМО.","delete_btn":"УДАЛИТЬ МОЙ АККАУНТ","cancel_btn":"ОТМЕНИТЬ ЗАПРОС","expiry":"Ссылки действительны 24 часа.","ignore":"Если вы не подавали этот запрос, проигнорируйте это письмо."}'::jsonb),
('gdpr', 'uk', 'Шановний користувач,', 'Ми отримали ваш запит на видалення облікового запису LiquiMixer.', 'З повагою,', 'LiquiMixer - Підтвердження видалення', '{"warning":"Усі дані будуть назавжди видалені, включаючи рецептури, продукти, налаштування та персональні дані.","irreversible":"Ця дія є БЕЗПОВОРОТНОЮ.","delete_btn":"ВИДАЛИТИ ОБЛІКОВИЙ ЗАПИС","cancel_btn":"СКАСУВАТИ ЗАПИТ","expiry":"Посилання дійсні 24 години.","ignore":"Якщо ви не подавали цей запит, ігноруйте цей лист."}'::jsonb),
('gdpr', 'sv', 'Hej,', 'Vi har mottagit din begäran om att radera ditt LiquiMixer-konto.', 'Med vänliga hälsningar,', 'LiquiMixer - Bekräftelse av kontoradering', '{"warning":"Observera att all din data kommer att raderas permanent, inklusive recept, produkter, inställningar och personuppgifter.","irreversible":"Denna åtgärd är OÅTERKALLELIG.","delete_btn":"RADERA MITT KONTO","cancel_btn":"AVBRYT BEGÄRAN","expiry":"Länkarna är giltiga i 24 timmar.","ignore":"Om du inte har gjort denna begäran kan du ignorera detta."}'::jsonb),
('gdpr', 'da', 'Hej,', 'Vi har modtaget din anmodning om at slette din LiquiMixer-konto.', 'Med venlig hilsen,', 'LiquiMixer - Bekræftelse af kontosletning', '{"warning":"Alle dine data vil blive permanent slettet, herunder opskrifter, produkter, indstillinger og personlige data.","irreversible":"Denne handling er UIGENKALDELIG.","delete_btn":"SLET MIN KONTO","cancel_btn":"ANNULLER ANMODNING","expiry":"Linkene udløber om 24 timer.","ignore":"Hvis du ikke har anmodet om dette, kan du ignorere denne email."}'::jsonb),
('gdpr', 'fi', 'Hei,', 'Olemme vastaanottaneet pyyntösi LiquiMixer-tilisi poistamiseksi.', 'Ystävällisesti,', 'LiquiMixer - Tilin poiston vahvistus', '{"warning":"Kaikki tietosi poistetaan pysyvästi, mukaan lukien reseptit, tuotteet, asetukset ja henkilötiedot.","irreversible":"Tämä toiminto on PERUUTTAMATON.","delete_btn":"POISTA TILINI","cancel_btn":"PERUUTA PYYNTÖ","expiry":"Linkit vanhenevat 24 tunnissa.","ignore":"Jos et ole tehnyt tätä pyyntöä, voit jättää tämän huomiotta."}'::jsonb),
('gdpr', 'no', 'Hei,', 'Vi har mottatt din forespørsel om å slette LiquiMixer-kontoen din.', 'Med vennlig hilsen,', 'LiquiMixer - Bekreftelse på kontosletting', '{"warning":"Alle dine data vil bli permanent slettet, inkludert oppskrifter, produkter, innstillinger og personlige data.","irreversible":"Denne handlingen er UGJENKALLELIG.","delete_btn":"SLETT MIN KONTO","cancel_btn":"AVBRYT FORESPØRSEL","expiry":"Lenkene utløper om 24 timer.","ignore":"Hvis du ikke har bedt om dette, kan du ignorere denne e-posten."}'::jsonb),
('gdpr', 'ja', 'こんにちは、', 'LiquiMixerアカウントの削除リクエストを受け付けました。', '敬具、', 'LiquiMixer - アカウント削除の確認', '{"warning":"すべてのデータが完全に削除されます。レシピ、製品、設定、個人データを含みます。","irreversible":"この操作は取り消しできません。","delete_btn":"アカウントを削除","cancel_btn":"リクエストをキャンセル","expiry":"リンクは24時間有効です。","ignore":"このリクエストを行っていない場合は、このメールを無視してください。"}'::jsonb),
('gdpr', 'ko', '안녕하세요,', 'LiquiMixer 계정 삭제 요청을 접수했습니다.', '감사합니다,', 'LiquiMixer - 계정 삭제 확인', '{"warning":"레시피, 제품, 설정 및 개인 데이터를 포함한 모든 데이터가 영구적으로 삭제됩니다.","irreversible":"이 작업은 되돌릴 수 없습니다.","delete_btn":"계정 삭제","cancel_btn":"요청 취소","expiry":"링크는 24시간 동안 유효합니다.","ignore":"이 요청을 하지 않았다면 이 이메일을 무시하십시오."}'::jsonb),
('gdpr', 'ar', 'مرحباً،', 'لقد تلقينا طلبكم لحذف حساب LiquiMixer.', 'مع التحيات،', 'LiquiMixer - تأكيد حذف الحساب', '{"warning":"يرجى العلم أن جميع بياناتكم ستُحذف نهائياً، بما في ذلك الوصفات والمنتجات والإعدادات والبيانات الشخصية.","irreversible":"هذا الإجراء لا رجعة فيه.","delete_btn":"حذف حسابي","cancel_btn":"إلغاء الطلب","expiry":"الروابط صالحة لمدة 24 ساعة.","ignore":"إذا لم تقدم هذا الطلب، يمكنك تجاهل هذا البريد الإلكتروني."}'::jsonb)
ON CONFLICT (template_key, lang) DO UPDATE SET greeting=EXCLUDED.greeting, body=EXCLUDED.body, sign_off=EXCLUDED.sign_off, subject_tpl=EXCLUDED.subject_tpl, extra=EXCLUDED.extra;

-- =============================================
-- WF6: Business/spam response emails
-- =============================================
INSERT INTO email_translations (template_key, lang, greeting, body, sign_off, subject_tpl) VALUES
('business_spam', 'cs', 'Dobrý den,', 'Děkujeme za Vaši zprávu. Bohužel na nevyžádané obchodní nabídky neodpovídáme. Pokud máte zájem o partnerství s LiquiMixer, kontaktujte nás prosím prostřednictvím oficiálních kanálů na našem webu.', 'S pozdravem,', 'Re: {{subject}}'),
('business_spam', 'sk', 'Dobrý deň,', 'Ďakujeme za Vašu správu. Bohužiaľ na nevyžiadané obchodné ponuky neodpovedáme. Ak máte záujem o partnerstvo s LiquiMixer, kontaktujte nás prosím prostredníctvom oficiálnych kanálov na našom webe.', 'S pozdravom,', 'Re: {{subject}}'),
('business_spam', 'en', 'Hello,', 'Thank you for your message. Unfortunately, we do not respond to unsolicited business offers. If you are interested in partnering with LiquiMixer, please contact us through official channels on our website.', 'Best regards,', 'Re: {{subject}}'),
('business_spam', 'de', 'Hallo,', 'Vielen Dank für Ihre Nachricht. Leider beantworten wir keine unaufgeforderten Geschäftsangebote. Wenn Sie an einer Partnerschaft mit LiquiMixer interessiert sind, kontaktieren Sie uns bitte über die offiziellen Kanäle auf unserer Website.', 'Mit freundlichen Grüßen,', 'Re: {{subject}}'),
('business_spam', 'fr', 'Bonjour,', 'Merci pour votre message. Malheureusement, nous ne répondons pas aux offres commerciales non sollicitées. Si vous êtes intéressé par un partenariat avec LiquiMixer, veuillez nous contacter via les canaux officiels sur notre site web.', 'Cordialement,', 'Re: {{subject}}'),
('business_spam', 'es', 'Hola,', 'Gracias por su mensaje. Lamentablemente, no respondemos a ofertas comerciales no solicitadas. Si está interesado en asociarse con LiquiMixer, contáctenos a través de los canales oficiales en nuestro sitio web.', 'Atentamente,', 'Re: {{subject}}'),
('business_spam', 'it', 'Salve,', 'Grazie per il suo messaggio. Purtroppo non rispondiamo a offerte commerciali non richieste. Se è interessato a una partnership con LiquiMixer, ci contatti attraverso i canali ufficiali sul nostro sito web.', 'Cordiali saluti,', 'Re: {{subject}}'),
('business_spam', 'pt', 'Olá,', 'Obrigado pela sua mensagem. Infelizmente, não respondemos a ofertas comerciais não solicitadas. Se estiver interessado em parceria com a LiquiMixer, entre em contato conosco pelos canais oficiais em nosso site.', 'Atenciosamente,', 'Re: {{subject}}'),
('business_spam', 'pl', 'Dzień dobry,', 'Dziękujemy za wiadomość. Niestety nie odpowiadamy na niezamówione oferty handlowe. Jeśli są Państwo zainteresowani współpracą z LiquiMixer, prosimy o kontakt przez oficjalne kanały na naszej stronie.', 'Z poważaniem,', 'Re: {{subject}}'),
('business_spam', 'tr', 'Merhaba,', 'Mesajınız için teşekkür ederiz. Maalesef talep edilmemiş ticari tekliflere yanıt vermiyoruz. LiquiMixer ile ortaklık kurmak istiyorsanız, lütfen web sitemizdeki resmi kanallardan bize ulaşın.', 'Saygılarımla,', 'Re: {{subject}}'),
('business_spam', 'ru', 'Здравствуйте,', 'Спасибо за ваше сообщение. К сожалению, мы не отвечаем на незапрошенные коммерческие предложения. Если вы заинтересованы в сотрудничестве с LiquiMixer, свяжитесь с нами через официальные каналы на нашем сайте.', 'С уважением,', 'Re: {{subject}}'),
('business_spam', 'nl', 'Hallo,', 'Bedankt voor uw bericht. Helaas reageren wij niet op ongewenste commerciële aanbiedingen. Als u geïnteresseerd bent in een samenwerking met LiquiMixer, neem dan contact met ons op via de officiële kanalen op onze website.', 'Met vriendelijke groet,', 'Re: {{subject}}'),
('business_spam', 'hu', 'Tisztelt Feladó,', 'Köszönjük üzenetét. Sajnos kéretlen üzleti ajánlatokra nem válaszolunk. Ha érdekli a LiquiMixerrel való együttműködés, kérjük, lépjen kapcsolatba velünk a weboldalunkon található hivatalos csatornákon keresztül.', 'Tisztelettel,', 'Re: {{subject}}'),
('business_spam', 'ro', 'Bună ziua,', 'Vă mulțumim pentru mesaj. Din păcate, nu răspundem ofertelor comerciale nesolicitate. Dacă sunteți interesat de un parteneriat cu LiquiMixer, vă rugăm să ne contactați prin canalele oficiale de pe site-ul nostru.', 'Cu stimă,', 'Re: {{subject}}')
ON CONFLICT (template_key, lang) DO UPDATE SET greeting=EXCLUDED.greeting, body=EXCLUDED.body, sign_off=EXCLUDED.sign_off, subject_tpl=EXCLUDED.subject_tpl;

-- Grant read access to service role (for N8N)
GRANT SELECT ON email_translations TO service_role;
GRANT SELECT ON email_translations TO anon;
