-- ============================================
-- BLOG ARTICLES TABLE
-- Runs on ANALYTICS DB (ikgtygabrrvbqyffcqjd)
-- NOT on production DB (krwdfxnvhnxtkhtkbadi)
-- ============================================
-- Workflow: proposal → topic_approved → draft → approved → translating → published
-- Generated by N8N, reviewed in LM Dashboard, served dynamically via edge function

CREATE TABLE IF NOT EXISTS blog_articles (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    
    -- Article grouping: all translations share the same article_group
    article_group UUID NOT NULL DEFAULT gen_random_uuid(),
    
    -- ===== FÁZE 1: TOPIC PROPOSAL (GPT-4 analýza) =====
    topic_proposal TEXT,                   -- Navržené téma (CZ)
    topic_reasoning TEXT,                  -- Odůvodnění proč toto téma (CZ)
    proposed_structure JSONB,              -- Navržená struktura článku [{"h2": "...", "points": ["..."]}]
    target_keywords_en TEXT[],             -- Cílová EN klíčová slova
    target_keywords_cs TEXT[],             -- Cílová CZ klíčová slova
    estimated_seo_impact TEXT,             -- Odhad SEO dopadu (low/medium/high)
    
    -- ===== FÁZE 2-4: ADMIN REVIEW =====
    admin_notes TEXT,                      -- Připomínky admina (pro GPT-4 přepracování)
    
    -- ===== FÁZE 3: CONTENT =====
    slug TEXT NOT NULL,                    -- URL-friendly identifier (e.g. "how-to-mix-e-liquid-beginners")
    locale TEXT NOT NULL DEFAULT 'cs',     -- Language code (cs, en, de, fr, ...)
    title TEXT NOT NULL DEFAULT '',        -- Article title
    meta_description TEXT,                 -- SEO meta description
    keywords TEXT[],                       -- SEO keywords array
    content TEXT NOT NULL DEFAULT '',      -- Full HTML content of the article
    excerpt TEXT,                          -- Short excerpt for listing pages
    
    -- ===== MÉDIA =====
    hero_image TEXT,                       -- Hero image URL (DALL-E generated, stored in Supabase Storage)
    inline_images JSONB DEFAULT '[]',      -- [{"url": "...", "alt": "...", "caption": "..."}]
    
    -- Classification
    category TEXT NOT NULL DEFAULT 'guide', -- guide, recipe, calculator, hookah, comparison
    
    -- Workflow status
    -- proposal: GPT-4 navrhl téma, čeká na schválení
    -- topic_approved: admin schválil téma, GPT-4 může psát článek
    -- draft: článek napsán v CZ, čeká na schválení obsahu
    -- approved: admin schválil článek, GPT-4 může překládat
    -- translating: překlad do 30 jazyků probíhá
    -- published: zveřejněno na blogu
    -- rejected: admin zamítl (téma nebo článek)
    -- archived: staženo z blogu
    status TEXT NOT NULL DEFAULT 'proposal',
    
    -- Metadata
    author TEXT DEFAULT 'LiquiMixer',
    og_image TEXT,                          -- Open Graph image URL (= hero_image or custom)
    published_at TIMESTAMPTZ,              -- When published (NULL = not published)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Constraints
    UNIQUE(slug, locale),
    CHECK (status IN ('proposal', 'topic_approved', 'draft', 'approved', 'translating', 'published', 'rejected', 'archived')),
    CHECK (locale ~ '^[a-z]{2}(-[A-Z]{2})?$')
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_blog_articles_status ON blog_articles(status);
CREATE INDEX IF NOT EXISTS idx_blog_articles_locale ON blog_articles(locale);
CREATE INDEX IF NOT EXISTS idx_blog_articles_slug_locale ON blog_articles(slug, locale);
CREATE INDEX IF NOT EXISTS idx_blog_articles_article_group ON blog_articles(article_group);
CREATE INDEX IF NOT EXISTS idx_blog_articles_published ON blog_articles(published_at DESC) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS idx_blog_articles_category ON blog_articles(category) WHERE status = 'published';

-- RLS policies
ALTER TABLE blog_articles ENABLE ROW LEVEL SECURITY;

-- Public read access for published articles only (anon key from blog edge function)
CREATE POLICY "Public can read published articles"
    ON blog_articles FOR SELECT
    USING (status = 'published');

-- Service role can do everything (for N8N + Dashboard + blog edge function admin actions)
CREATE POLICY "Service role full access"
    ON blog_articles FOR ALL
    USING (auth.role() = 'service_role');

-- ============================================
-- Storage bucket for blog media (images, videos)
-- ============================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('blog-media', 'blog-media', true)
ON CONFLICT (id) DO NOTHING;

-- Public read access for blog media
CREATE POLICY "Public read blog media"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'blog-media');

-- Service role can upload blog media
CREATE POLICY "Service role upload blog media"
    ON storage.objects FOR INSERT
    WITH CHECK (bucket_id = 'blog-media' AND auth.role() = 'service_role');

CREATE POLICY "Service role delete blog media"
    ON storage.objects FOR DELETE
    USING (bucket_id = 'blog-media' AND auth.role() = 'service_role');

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_blog_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER blog_articles_updated_at
    BEFORE UPDATE ON blog_articles
    FOR EACH ROW
    EXECUTE FUNCTION update_blog_updated_at();

-- Auto-set published_at when status changes to 'published'
CREATE OR REPLACE FUNCTION set_blog_published_at()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'published' AND OLD.status != 'published' THEN
        NEW.published_at = NOW();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER blog_articles_set_published
    BEFORE UPDATE ON blog_articles
    FOR EACH ROW
    EXECUTE FUNCTION set_blog_published_at();
